#  Copyright (c) 2020. Vinci Consulting Corp. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

ADJACENCY_COUNTERS_ENABLE = "adjacency counters enable"
CLEAR_ACLPLUGIN_SESSIONS = "clear acl-plugin sessions"
CLEAR_ERRORS = "clear errors"
CLEAR_INTERFACES = "clear interfaces"
CLEAR_IPSEC_COUNTERS = "clear ipsec counters"
CLEAR_IPSEC_SA = "clear ipsec sa"
CLEAR_LOGGING = "clear logging"
CLEAR_TRACE = "clear trace"
FLOWPROBE_FEATURE_ADDDEL_X_X_DISABLE = \
    "flowprobe feature add-del %s %s disable"
IPFIX_FLUSH = "ipfix flush"
LB_VIP_X_ENCAP_GRE4 = "lb vip %s encap gre4"
LB_VIP_X_ENCAP_GRE6 = "lb vip %s encap gre6"
MAP_PARAMS_PRERESOLVE_DEL_IP6NH_X = "map params pre-resolve del ip6-nh %s"
MAP_PARAMS_PRERESOLVE_IP6NH_X = "map params pre-resolve ip6-nh %s"
PACKETGENERATOR_DELETESTREAM_X = "packet-generator delete %s"
PACKETGENERATOR_ENABLESTREAM = "packet-generator enable-stream"
PACKETGENERATOR_ENABLESTREAM_X = "packet-generator enable-stream %s"
SET_ACLPLUGIN_SESSION_TIMEOUT_TCP_IDLE_X = \
    "set acl-plugin session timeout tcp idle %s"
SET_ACLPLUGIN_SESSION_TIMEOUT_TCP_TRANSIENT_X = \
    "set acl-plugin session timeout tcp transient %s"
SET_ACLPLUGIN_SESSION_TIMEOUT_UDP_IDLE_X = \
    "set acl-plugin session timeout udp idle %s"
SET_CRYPTO_HANDLER_ALL_X = "set crypto handler all %s"
SET_IPFIX_EXPORTER_COLLECTOR_X = "set ipfix exporter collector %s"
SET_LOGGING_CLASS_BFD_LEVEL_DEBUG = "set logging class bfd level debug"
SET_LOGGING_CLASS_GBP_LEVEL_DEBUG = "set logging class gbp level debug"
SET_LOGGING_CLASS_IGMP_LEVEL_DEBUG = "set logging class igmp level debug"
SET_LOGGING_CLASS_IPSEC_LEVEL_DEBUG = "set logging class ipsec level debug"
SET_LOGGING_CLASS_NAT_LEVEL_DEBUG = "set logging class nat level debug"
SET_QUIC_FIFOSIZE_X = "quic set fifo-size %s"
SET_SR_ENCAPS_SOURCE_ADDR_X = "set sr encaps source addr %s"
SHOW_ACLPLUGIN_ACL = "show acl-plugin acl"
SHOW_ACLPLUGIN_INTERFACE = "show acl-plugin interface"
SHOW_ACLPLUGIN_MACIP_ACL = "show acl-plugin macip acl"
SHOW_ACLPLUGIN_MACIP_ACL_INDEX_X = "show acl-plugin macip acl index %s"
SHOW_ACLPLUGIN_MACIP_INTERFACE = "show acl-plugin macip interface"
SHOW_ACLPLUGIN_SESSIONS = "show acl-plugin sessions"
SHOW_ACLPLUGIN_SESSIONS_VERBOSE_X = "show acl-plugin sessions verbose %s"
SHOW_ACLPLUGIN_TABLES = "show acl-plugin tables"
SHOW_ADJ = "show adj"
SHOW_ADJ_NBR = "show adj nbr"
SHOW_BFD = "show bfd"
SHOW_BFD_KEYS = "show bfd keys"
SHOW_BFD_SESSIONS = "show bfd sessions"
SHOW_BIHASH = "show bihash"
SHOW_BRIDGEDOMAIN = "show bridge-domain"
SHOW_BRIDGEDOMAIN_X_DETAIL = "show bridge-domain %s detail"
SHOW_BUFFERS = "show buffers"
SHOW_CDP = "show cdp"
SHOW_CLASSIFY_TABLES = "show classify tables"
SHOW_CLASSIFY_TABLES_VERBOSE = "show classify tables verbose"
SHOW_CLASSIFY_TABLES_VERBOSE_X = "show classify tables verbose %s"
SHOW_DHCP_CLIENT_INTFC_X_VERBOSE = "show dhcp client intfc %s verbose"
SHOW_DNS_CACHE_VERBOSE = "show dns cache verbose"
SHOW_DSLITE_AFTRTUNNELENDPOINTADDRESS = \
    "show dslite aftr-tunnel-endpoint-address"
SHOW_DSLITE_B4TUNNELENDPOINTADDRESS = "show dslite b4-tunnel-endpoint-address"
SHOW_DSLITE_POOL = "show dslite pool"
SHOW_DSLITE_SESSIONS = "show dslite sessions"
SHOW_ERRORS = "show errors"
SHOW_EVENTLOGGER_ALL = "show event-logger all"
SHOW_GBP_BRIDGE = "show gbp bridge"
SHOW_GBP_CONTRACT = "show gbp contract"
SHOW_GBP_ENDPOINT = "show gbp endpoint"
SHOW_GBP_ENDPOINTGROUP = "show gbp endpoint-group"
SHOW_GBP_INTERFACE = "shoe gbp interface"
SHOW_GBP_RECIRC = "show gbp recirc"
SHOW_GBP_ROUTE = "show gbp route"
SHOW_GBP_VXLAN = "show gbp vxlan"
SHOW_GENEVE_TUNNEL = "show geneve tunnel"
SHOW_GTPU_TUNNEL = "show gtpu tunnel"
SHOW_HARDWARE = "show hardware"
SHOW_IGMP_CONFIG = "show igmp config"
SHOW_INACL_TYPE_IP4 = "show inacl type ip4"
SHOW_INACL_TYPE_IP6 = "show inacl type ip6"
SHOW_INTERFACE = "show interface"
SHOW_INTERFACE_ADDRESS = "show interface address"
SHOW_INTERFACE_FEAT_X = "show interface feat %s"
SHOW_INTERFACE_SPAN = "show interface span"
SHOW_IP_FIB = "show ip fib"
SHOW_IP_FIB_MTRIE = "show ip fib mtrie"
SHOW_IP_FIB_X = "show ip fib %s"
SHOW_IP_MFIB = "show ip mfib"
SHOW_IP_NEIGHBORCONFIG = "show ip neighbor-config"
SHOW_IP_NEIGHBORS = "show ip neighbors"
SHOW_IP_NEIGHBORSORTED = "sh ip4 neighbor-sorted"
SHOW_IP_NEIGHBORWATCHER = "show ip neighbor-watcher"
SHOW_IPIP_TUNNELHAS = "show ipip tunnel-has"
SHOW_IPSEC_ALL = "show ipsec all"
SHOW_IPSEC_PROTECTHASH = "show ipsec protect-hash"
SHOW_IPSEC_SA = "show ipsec sa"
SHOW_IPSEC_SA_X = "show ipsec sa %s"
SHOW_IPSEC_TUN = "sh ipsec tun"
SHOW_IP4FULLREASSEMBLY_DETAILS = "show ip4-full-reassembly details"
SHOW_IP4SVREASSEMBLY_DETAILS = "show ip4-sv-reassembly details"
SHOW_IP6_FIB = "show ip6 fib"
SHOW_IP6_FIB_X = "show ip6 fib %s"
SHOW_IP6FULLREASSEMBLY_DETAILS = "show ip6-full-reassembly details"
SHOW_IP6SVREASSEMBLY_DETAILS = "show ip6-sv-reassembly details"
SHOW_IP6_NEIGHBORS = "show ip6 neighbors"
SHOW_LB_VIP_VERBOSE = "show lb vip verbose"
SHOW_LOG = "show log"
SHOW_L2FIB = "show l2fib"
SHOW_L2FIB_BDID_X = "show l2fib bd_id %s"
SHOW_L2FIB_VERBOSE = "show l2fib verbose"
SHOW_L2PATCH = "show l2patch"
SHOW_L3CX = "show l3xc"
SHOW_NAT_ADDRPORTASSIGNMENTALG = "show nat addr-port-assignment-alg"
SHOW_NAT_HA = "show nat ha"
SHOW_NAT_TIMEOUTS = "show nat timeouts"
SHOW_NAT44_ADDRESSES = "show nat44 addresses"
SHOW_NAT44_DETERMINISTIC_MAPPINGS = "show nat44 deterministic mappings"
SHOW_NAT44_DETERMINISTIC_SESSIONS = "show nat44 deterministic sessions"
SHOW_NAT44_HASH_TABLES_DETAIL = "show nat44 hash tables detail"
SHOW_NAT44_INTERFACE_ADDRESS = "show nat44 interface address"
SHOW_NAT44_INTERFACES = "show nat44 interfaces"
SHOW_NAT44_SESSIONS_DETAIL = "show nat44 sessions detail"
SHOW_NAT44_STATIC_MAPPINGS = "show nat44 static mappings"
SHOW_NAT64_BIB_ALL = "show nat64 bib all"
SHOW_NAT64_INTERFACES = "show nat64 interfaces"
SHOW_NAT64_POOL = "show nat64 pool"
SHOW_NAT64_PREFIX = "show nat64 prefix"
SHOW_NAT64_SESSION_TABLE_ALL = "show nat64 session table all"
SHOW_NAT66_INTERFACE = "show nat66 interface"
SHOW_NAT66_STATIC_MAPPINGS = "show nat66 static mappings"
SHOW_OUTACL_TYPE_IP4 = "show outacl type ip4"
SHOW_OUTACL_TYPE_IP6 = "show outacl type ip6"
SHOW_PPPOE_FIB = "show pppoe fib"
SHOW_PPPOE_SESSION = "show pppoe session"
SHOW_PUNT_SOCKET_REGISTRATIONS = "show punt socket registrations"
SHOW_PUNT_SOCKET_REGISTRATION_EXCEPTION = \
    "show punt socket registration exception"
SHOW_PUNT_SOCKET_REGISTRATION_IP = "show punt socket registration ip"

SHOW_PUNT_CLIENT = "show punt client"
SHOW_PUNT_DB = "show punt db"
SHOW_PUNT_REASON = "show punt reason"
SHOW_PUNT_STATS = "show punt stats"
SHOW_QOS_EGRESS_MAP = "show qos egress map"
SHOW_QOS_MARK = "show qos mark"
SHOW_QOS_RECORD = "show qos record"
SHOW_QOS_STORE = "show qos store"
SHOW_RUN = "show run"
SHOW_SR_LOCALSID = "show sr localsid"
SHOW_SR_POLICIES = "show sr policies"
SHOW_SR_STEERING_POLICIES = "show sr steering-policies"
SHOW_TRACE = "show trace"
SHOW_TRACE_MAX_X = "show trace max %s"
SHOW_UDP_ENCAP = "show udp encap"
SHOW_VLIB_GRAPH = "show vlib graph"
SHOW_VLIB_GRAPH_L2INPUTFEATARC = "show vlib graph l2-input-feat-arc"
SHOW_VLIB_GRAPH_L2INPUTFEATARCEND = "show vlib graph l2-input-feat-arc-end"
SHOW_VLIB_GRAPH_L2OUTPUTFEATARC = "show vlib graph l2-output-feat-arc"
SHOW_VLIB_GRAPH_L2OUTPUTFEATARCEND = "show vlib graph l2-output-feat-arc-end"
SHOW_VLIB_GRAPH_X = "show vlib graph %s"
SHOW_VRRP_VR = "show vrrp vr"
SHOW_VXLAN_TUNNEL = "show vxlan tunnel"
SHOW_VXLANGBE_TUNNEL = "show vxlan-gbe tunnel"
SHOW_VXLANGBP_TUNNEL = "show vxlan-gbp tunnel"
SR_LOCALSID_DEL_ADDRESS_X = "sr localsid del address %s"
TEST_FIBWALKPROCESS_DISABLE = "test fib-walk-process disable"
TEST_FIBWALKPROCESS_ENABLE = "test fib-walk-process enable"
TEST_HTTP_SERVER = "test http server"
TEST_LB_FLOWTABLE_FLUSH = "test lb flowtable flush"
TRACE_ADD_P2PETHERNETINPUT_X = "trace add p2p-ethernet-input %s"
