
/* The first version is autogenerated using the logic from build-root/build-vpp_debug-native/vpp/plugins/acl/acl.api_types.h */

/*
build-root/build-vpp_debug-native/vpp/plugins/acl/acl.api.h:_(VL_API_ACL_ADD_REPLACE, acl_add_replace, 13bc8539) \
build-root/build-vpp_debug-native/vpp/plugins/acl/acl.api.h:_(VL_API_ACL_ADD_REPLACE_REPLY, acl_add_replace_reply, ac407b0c) \
*/

typedef struct __attribute__ ((packed)) _vl_api_acl_rule_deadbeef {
    u8 is_permit;
    u8 is_ipv6;
    u8 src_ip_addr[16];
    u8 src_ip_prefix_len;
    u8 dst_ip_addr[16];
    u8 dst_ip_prefix_len;
    u8 proto;
    u16 srcport_or_icmptype_first;
    u16 srcport_or_icmptype_last;
    u16 dstport_or_icmpcode_first;
    u16 dstport_or_icmpcode_last;
    u8 tcp_flags_mask;
    u8 tcp_flags_value;
} vl_api_acl_rule_deadbeef_t;


typedef struct __attribute__ ((packed)) _vl_api_acl_add_replace_13bc8539 {
    u16 _vl_msg_id;
    u32 client_index;
    u32 context;
    u32 acl_index;
    u8 tag[64];
    u32 count;
    vl_api_acl_rule_deadbeef_t r[0];
} vl_api_acl_add_replace_13bc8539_t;

typedef struct __attribute__ ((packed)) _vl_api_acl_add_replace_reply_ac407b0c {
    u16 _vl_msg_id;
    u32 context;
    u32 acl_index;
    i32 retval;
} vl_api_acl_add_replace_reply_ac407b0c_t;



