#!/usr/bin/env python3
#
# Copyright 2026 Rubicon Communications, LLC (Netgate)
#
# SPDX-License-Identifier: Apache-2.0
#

"""Generate Python type stubs for vpp_papi VAPI methods.

This script runs at build time, collecting .python.json descriptors
generated by vppapigen_python.py plugin, and produces:
  - vapi_types.py: Type stubs for VppApiDynamicMethodHolder
  - vpp_papi_provider.pyi: Type stubs for VppPapiProvider (test framework)

Usage:
    generate_python_stubs.py [options]

The script first generates .python.json descriptors by running vppapigen
with the Python plugin, then collects them and produces the final stubs.
"""

import argparse
import json
import os
import pathlib
import subprocess
import sys
from typing import Any

# Add vppapigen directory to path
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)

import vppapigen

BASE_DIR = (
    subprocess.check_output("git rev-parse --show-toplevel", shell=True)
    .strip()
    .decode()
)

# Directories searched for .api files
SRC_DIR_DEPTH = 3
OUTPUT_DIR_MAP = {
    "plugins": "plugins",
    "vlibmemory": "core",
    "vnet": "core",
    "vlib": "core",
    "vpp": "core",
}

# Internal VPP API fields excluded from method signatures
INTERNAL_FIELDS = {"_vl_msg_id", "client_index", "context"}


def find_api_files(src_dir: pathlib.Path) -> list[pathlib.Path]:
    """Find all .api files in the source tree."""
    print(f"Searching '{src_dir.as_posix()}' for .api files.")
    globs = []
    for g in OUTPUT_DIR_MAP:
        globs.extend(list(src_dir.glob(f"{g}/**/*.api")))
    return sorted(globs)


def get_output_subdir(api_path: pathlib.Path) -> str:
    """Get the output subdirectory for an .api file."""
    parts = api_path.as_posix().split("/")
    # Find the component that matches one of our source directories
    for _idx, part in enumerate(parts):
        if part in OUTPUT_DIR_MAP:
            return OUTPUT_DIR_MAP[part]
    return "core"


def run_vppapigen_for_file(
    api_file: pathlib.Path,
    output_dir: pathlib.Path,
    src_dir: pathlib.Path,
    output_module: str = "Python",
) -> None:
    """Run vppapigen on a single .api file with the given output module."""
    output_subdir = get_output_subdir(api_file)
    filename = api_file.stem

    out_path = output_dir / output_subdir
    out_path.mkdir(parents=True, exist_ok=True)

    _ = vppapigen.run_vppapigen(
        input_file=api_file.as_posix(),
        output=str(out_path / f"{filename}.python.json"),
        outputdir=str(out_path),
        includedir=[src_dir.as_posix()],
        output_module=output_module,
    )


def collect_descriptors(output_dir: pathlib.Path) -> list[Any]:
    """Collect all .python.json descriptors from the output directory."""
    descriptors = []
    for json_file in sorted(output_dir.glob("**/*.python.json")):
        with open(json_file, "r", encoding="UTF-8") as f:
            descriptors.append(json.load(f))
    return descriptors


def _normalize_type(type_str: str) -> str:
    """Normalize a type string for use in stubs.

    Strips 'VppEnum.' prefix since enum types are standalone IntEnum classes
    in the generated stub, not attributes of a VppEnum class.
    """
    return type_str.replace("VppEnum.", "")


def _widen_input_type(
    type_str: str, typedef_union_names: set[str], enum_names: set[str]
) -> str:
    """Widen a type for use in an input position (parameter or TypedDict field).

    - typedef / union refs become `T | Mapping[str, Any]`, so callers may pass
      either a literal-key dict or a programmatically-built mapping
    - enum refs become `T | int`, since vpp_papi accepts plain integers at
      runtime and existing test code commonly uses numeric literals
    - `list[T]` becomes `Sequence[<widened T>]`. Sequence rather than list
      because list is invariant: pyright would refuse `list[str]` where
      `list[IPv4Network | str]` is declared. Sequence is covariant.
    """
    if type_str.startswith("list[") and type_str.endswith("]"):
        inner = type_str[5:-1]
        if inner in typedef_union_names:
            return f"Sequence[{inner} | Mapping[str, Any]]"
        if inner in enum_names:
            return f"Sequence[{inner} | int]"
        return f"Sequence[{inner}]"
    if type_str in typedef_union_names:
        return f"{type_str} | Mapping[str, Any]"
    if type_str in enum_names:
        return f"{type_str} | int"
    return type_str


def generate_field_annotation(
    field: dict[str, Any],
    typedef_union_names: set[str] | None = None,
    enum_names: set[str] | None = None,
    output_mode: bool = False,
) -> str:
    """Generate a field annotation string.

    - `output_mode=True`: use the field's `output_type` (already resolved by the
      plugin to use NamedTuple twins for typedef refs and tighter SPECIAL_OUTPUT
      types — no `str` fallback that vpp_papi never returns at decode time).
    - `typedef_union_names`/`enum_names` provided (and not output_mode): widen
      typedef/union refs to accept Mapping[str, Any] and enum refs to accept
      int (used for input-position TypedDict fields and method parameters).
    - Neither: leave the type as-is."""
    if output_mode:
        field_type = _normalize_type(field.get("output_type", field.get("type", "Any")))
    else:
        field_type = _normalize_type(field.get("type", "Any"))
        if typedef_union_names is not None:
            field_type = _widen_input_type(
                field_type, typedef_union_names, enum_names or set()
            )
    return f"{field['name']}: {field_type}"


def generate_typeddict_class(
    name: str,
    fields: list[dict[str, Any]],
    typedef_union_names: set[str],
    enum_names: set[str],
    comment: str = "",
    total: bool = True,
) -> str:
    """Generate a TypedDict class definition for a typedef/union."""
    lines = []
    if comment:
        lines.append(f'    """{comment}"""')
    else:
        lines.append(f'    """Auto-generated TypedDict for {name}."""')

    if not fields:
        lines.append("    pass")
    else:
        for field in fields:
            lines.append(
                f"    {generate_field_annotation(field, typedef_union_names, enum_names)}"
            )

    body = "\n".join(lines)
    header = (
        f"class {name}(TypedDict)" if total else f"class {name}(TypedDict, total=False)"
    )
    return f"{header}:\n{body}\n"


def generate_namedtuple_class(
    name: str,
    fields: list[dict[str, Any]],
    comment: str = "",
) -> str:
    """Generate a NamedTuple class definition. Used for reply messages and for
    the `_nt` NamedTuple twins of typedefs/unions. Each field's `output_type`
    (precomputed by the plugin) is used so typedef/union refs point at their
    `_nt` twins and special types drop the `str` input alternative."""
    lines = []
    if comment:
        lines.append(f'    """{comment}"""')
    else:
        lines.append(f'    """Auto-generated NamedTuple for {name}."""')

    if not fields:
        lines.append("    pass")
    else:
        for field in fields:
            lines.append(f"    {generate_field_annotation(field, output_mode=True)}")

    body = "\n".join(lines)
    return f"class {name}(NamedTuple):\n{body}\n"


def generate_enum_class(enum: dict[str, Any]) -> str:
    """Generate an IntEnum class definition."""
    name = enum["full_name"]
    entries = enum.get("entries", [])

    lines = [f"class {name}(IntEnum):"]
    if not entries:
        lines.append("    pass")
    else:
        for entry in entries:
            lines.append(f"    {entry['id']} = {entry['value']}")

    return "\n".join(lines) + "\n"


def generate_method_signature(
    svc: dict[str, Any],
    typedef_union_names: set[str],
    enum_names: set[str],
    defaulted_params: set[str] | None = None,
) -> tuple[str, str]:
    """Generate a method signature and return type annotation.

    `defaulted_params`, if given, names parameters with runtime-supplied
    defaults (from the provider's defaultmapping table). Once any parameter
    in declaration order has a default, all subsequent parameters get `= ...`
    too — Python forbids required parameters after defaulted ones, so we
    cascade rather than reorder (which would break positional callers).

    Returns:
        (method_line, return_type_name_or_None)
    """
    name = svc["name"]
    params = svc.get("params", [])
    return_info = svc.get("return_type")
    defaulted_params = defaulted_params or set()

    # Build parameter list (excluding internal fields). Method parameters are an
    # input position: typedef/union refs are widened to also accept Mapping,
    # and enum refs to accept int.
    param_parts = []
    after_default = False
    for p in params:
        if p["name"] in INTERNAL_FIELDS:
            continue
        ptype = _widen_input_type(
            _normalize_type(p["type"]), typedef_union_names, enum_names
        )
        if p["name"] in defaulted_params:
            after_default = True
        suffix = " = ..." if after_default else ""
        param_parts.append(f"{p['name']}: {ptype}{suffix}")

    params_str = ", ".join(param_parts)

    # Build return type
    if return_info:
        kind = return_info["kind"]
        if kind == "single":
            ret_type = _normalize_type(return_info["reply_type"])
        elif kind == "stream_modern":
            ret_type = f"tuple[{_normalize_type(return_info['reply_type'])}, list[{_normalize_type(return_info['details_type'])}]]"
        elif kind == "stream_legacy":
            ret_type = f"list[{_normalize_type(return_info['details_type'])}]"
        else:
            ret_type = "Any"
    else:
        ret_type = "Any"

    method_line = f"    def {name}(self, {params_str}) -> {ret_type}: ..."
    return method_line, ret_type


def generate_vapi_types(descriptors: list[Any], output_path: str) -> None:
    """Generate vapi_types.py from collected descriptors."""

    # Collect all types across all files for cross-reference resolution
    all_messages = {}  # name -> message descriptor
    all_types = {}  # full_name -> typedef descriptor
    all_enums = {}  # full_name -> enum descriptor
    all_unions = {}  # full_name -> union descriptor
    all_aliases = {}  # full_name -> alias descriptor
    all_services = []  # list of service descriptors

    for desc in descriptors:
        for msg in desc.get("messages", []):
            all_messages[msg["name"]] = msg
        for tdef in desc.get("typedefs", []):
            all_types[tdef["full_name"]] = tdef
        for enum in desc.get("enums", []):
            all_enums[enum["full_name"]] = enum
        for union in desc.get("unions", []):
            all_unions[union["full_name"]] = union
        for alias in desc.get("aliases", []):
            all_aliases[alias["full_name"]] = alias
        for svc in desc.get("services", []):
            all_services.append(svc)

        # Build output
    lines = [
        "# Auto-generated type hints for vpp_papi VAPI methods.",
        "# Generated by generate_python_stubs.py at build time.",
        "#",
        "# Usage:",
        "#     from vpp_papi.vapi_types import VppApiDynamicMethodHolder",
        "#     def foo(api: VppApiDynamicMethodHolder) -> None:",
        "#         api.bfd_udp_add(sw_if_index=1, ...)  # type-checked!",
        "",
        "from __future__ import annotations",
        "",
        "import datetime",
        "import ipaddress",
        "from collections.abc import Mapping, Sequence",
        "from enum import IntEnum",
        "from typing import Any, NamedTuple, TypeAlias, TypedDict",
        "",
        "from . import MACAddress",
        "",
    ]

    typedef_union_names = set(all_types.keys()) | set(all_unions.keys())
    enum_names = set(all_enums.keys())

    # Generate TypeAlias declarations for Using nodes (e.g. typedef u32 interface_index).
    # Skip aliases whose name is in SPECIAL_INPUT_TYPES — references to those names
    # are rewritten to the special union type before reaching the alias.
    emitted_aliases = [
        alias for alias in all_aliases.values() if not alias.get("in_special_input")
    ]
    if emitted_aliases:
        lines.append("# Type aliases")
        for alias in sorted(emitted_aliases, key=lambda a: a["full_name"]):
            lines.append(f"{alias['full_name']}: TypeAlias = {alias['python_type']}")
        lines.append("")

    # Generate TypedDict classes for typedefs (used as dict parameters)
    if all_types:
        lines.append("# Type definitions")
        for full_name in sorted(all_types.keys()):
            tdef = all_types[full_name]
            lines.append(
                generate_typeddict_class(
                    full_name,
                    tdef.get("fields", []),
                    typedef_union_names,
                    enum_names,
                    comment=f"TypedDict for {tdef['name']}",
                )
            )
        lines.append("")

    # Generate TypedDict classes for unions (used as dict parameters)
    if all_unions:
        lines.append("# Union types")
        for full_name in sorted(all_unions.keys()):
            union = all_unions[full_name]
            lines.append(
                generate_typeddict_class(
                    full_name,
                    union.get("fields", []),
                    typedef_union_names,
                    enum_names,
                    comment=f"TypedDict for union {union['name']}",
                    total=False,
                )
            )
        lines.append("")

    # Generate NamedTuple twins for typedefs / unions. The same .api typedef can
    # flow into both directions (e.g. set_parameters takes a parameters typedef
    # as input; get_parameters returns it inside a reply). The TypedDict form is
    # for input (literal-key dict construction); this `_nt` NamedTuple form is
    # what callers see when reading replies, where attribute access is the
    # natural style and matches what vpp_papi decodes typedefs into at runtime
    # (collections.namedtuple).
    if all_types or all_unions:
        lines.append("# NamedTuple twins for typedefs/unions (decoded reply form)")
        for full_name in sorted(all_types.keys()):
            tdef = all_types[full_name]
            lines.append(
                generate_namedtuple_class(
                    f"{full_name}_nt",
                    tdef.get("fields", []),
                    comment=f"NamedTuple twin of {tdef['name']} (decoded form)",
                )
            )
        for full_name in sorted(all_unions.keys()):
            union = all_unions[full_name]
            lines.append(
                generate_namedtuple_class(
                    f"{full_name}_nt",
                    union.get("fields", []),
                    comment=f"NamedTuple twin of union {union['name']} (decoded form)",
                )
            )
        lines.append("")

    # Generate NamedTuple classes for reply messages
    # First, determine which messages are used as return types
    reply_types = set()
    for svc in all_services:
        ret = svc.get("return_type")
        if ret:
            if ret["kind"] == "single":
                reply_types.add(ret["reply_type"])
            elif ret["kind"] == "stream_modern":
                reply_types.add(ret["reply_type"])
                reply_types.add(ret["details_type"])
            elif ret["kind"] == "stream_legacy":
                reply_types.add(ret["details_type"])

    if reply_types:
        lines.append("# Reply message types")
        for full_name in sorted(reply_types):
            # Find the message by stripping vl_api_ prefix and _t suffix
            msg_name = full_name.removeprefix("vl_api_").removesuffix("_t")
            msg = all_messages.get(msg_name)
            if msg:
                lines.append(
                    generate_namedtuple_class(
                        full_name,
                        msg.get("fields", []),
                        comment=f"Reply message type for {msg_name}",
                    )
                )
            else:
                # Message not found (might be in imported types)
                lines.append(f"class {full_name}(NamedTuple):\n    pass\n")
        lines.append("")

    # Generate enum classes
    if all_enums:
        lines.append("# Enum types")
        for full_name in sorted(all_enums.keys()):
            enum = all_enums[full_name]
            lines.append(generate_enum_class(enum))
        lines.append("")

    # Generate VppApiDynamicMethodHolder class
    lines.append("")
    lines.append("class VppApiDynamicMethodHolder:")
    lines.append('    """Type hints for dynamically created VAPI methods."""')
    lines.append("")

    # Sort services by name for consistent output
    sorted_services = sorted(all_services, key=lambda s: s["name"])
    for svc in sorted_services:
        method_line, _ = generate_method_signature(svc, typedef_union_names, enum_names)
        lines.append(method_line)
        lines.append("")

    stub_content = "\n".join(lines)

    with open(output_path, "w", encoding="UTF-8") as f:
        f.write(stub_content)

    print(f"Generated: {output_path} ({len(sorted_services)} methods)")


def _strip_generics(type_str: str) -> str:
    """Strip generic parameters from a type string.

    E.g. 'list[vl_api_acl_rule_t]' -> 'list'
         'tuple[vl_api_reply_t, list[vl_api_detail_t]]' -> 'tuple'
    """
    bracket_pos = type_str.find("[")
    if bracket_pos != -1:
        return type_str[:bracket_pos]
    return type_str


def _split_union_type(type_str: str) -> list[str]:
    """Split a union type string on ' | ', respecting bracket depth."""
    parts: list[str] = []
    current: list[str] = []
    depth = 0
    tokens = type_str.split(" ")
    for token in tokens:
        if token == "|" and depth == 0:
            part = " ".join(current).strip()
            if part:
                parts.append(part)
            current = []
        else:
            current.append(token)
            depth += token.count("[")
            depth -= token.count("]")
    part = " ".join(current).strip()
    if part:
        parts.append(part)
    return parts


def _collect_used_types(all_services: list[dict[str, Any]]) -> set[str]:
    """Collect all type names referenced in method signatures."""
    types: set[str] = set()
    for svc in all_services:
        for p in svc.get("params", []):
            if p["name"] not in INTERNAL_FIELDS:
                types.add(_normalize_type(p["type"]))
        ret = svc.get("return_type")
        if ret:
            kind = ret["kind"]
            if kind == "single":
                types.add(_normalize_type(ret["reply_type"]))
            elif kind == "stream_modern":
                types.add(_normalize_type(ret["reply_type"]))
                types.add(_normalize_type(ret["details_type"]))
            elif kind == "stream_legacy":
                types.add(_normalize_type(ret["details_type"]))
    return types


def parse_defaultmapping(provider_path: pathlib.Path) -> dict[str, set[str]]:
    """Parse the `defaultmapping` dict in test/vpp_papi_provider.py and return
    a mapping from method name to the set of parameter names with runtime
    defaults. The values themselves don't matter for stub generation — some
    entries use non-literal expressions like `os.getpid()` so we walk the AST
    and pull out only the keys."""
    import ast

    if not provider_path.is_file():
        return {}

    with open(provider_path, "r", encoding="UTF-8") as f:
        tree = ast.parse(f.read())

    result: dict[str, set[str]] = {}
    for node in ast.walk(tree):
        if not isinstance(node, ast.Assign):
            continue
        if len(node.targets) != 1:
            continue
        target = node.targets[0]
        if not isinstance(target, ast.Name) or target.id != "defaultmapping":
            continue
        if not isinstance(node.value, ast.Dict):
            continue
        for k, v in zip(node.value.keys, node.value.values):
            if not isinstance(k, ast.Constant) or not isinstance(k.value, str):
                continue
            if not isinstance(v, ast.Dict):
                continue
            params: set[str] = set()
            for pk in v.keys:
                if isinstance(pk, ast.Constant) and isinstance(pk.value, str):
                    params.add(pk.value)
            result[k.value] = params
        break
    return result


def generate_provider_stub(
    descriptors: list[Any],
    output_path: str,
    defaultmapping: dict[str, set[str]] | None = None,
) -> None:
    """Generate vpp_papi_provider.pyi for the test framework."""

    defaultmapping = defaultmapping or {}

    # Collect all services and the typedef/union/enum name sets used to widen
    # input-position references.
    all_services = []
    typedef_union_names: set[str] = set()
    enum_names: set[str] = set()
    for desc in descriptors:
        for svc in desc.get("services", []):
            all_services.append(svc)
        for tdef in desc.get("typedefs", []):
            typedef_union_names.add(tdef["full_name"])
        for union in desc.get("unions", []):
            typedef_union_names.add(union["full_name"])
        for enum in desc.get("enums", []):
            enum_names.add(enum["full_name"])

    # Methods already explicitly declared
    explicit_methods = {"cli", "ppcli", "cli_return_response", "api"}

    # Collect all types used in method signatures and determine imports
    all_types = _collect_used_types(all_services)
    # Filter to only types defined in vapi_types (vl_api_*_t and VppEnum)
    importable_types: set[str] = set()
    for type_str in all_types:
        for part in _split_union_type(type_str):
            # Strip generic params (list[X] -> list) then get base name
            stripped = _strip_generics(part)
            base = stripped.split(".")[0] if "." in stripped else stripped
            # Import top-level names from vapi_types
            # (vl_api_*_t NamedTuples, IntEnums, etc.)
            # Skip built-ins and stdlib types
            if base not in (
                "int",
                "str",
                "bool",
                "float",
                "list",
                "dict",
                "tuple",
                "set",
                "frozenset",
                "bytes",
                "bytearray",
                "None",
                "datetime",
                "ipaddress",
                "Any",
                "Callable",
                "Mapping",
                "NamedTuple",
                "Sequence",
            ):
                importable_types.add(base)

    # Build import lines
    import_lines: list[str] = []
    if importable_types:
        sorted_types = sorted(importable_types)
        # Format as multi-line import for readability
        import_lines.append("from vpp_papi.vapi_types import (")
        for t in sorted_types:
            import_lines.append(f"    {t},")
        import_lines.append(")")
        import_lines.append("")

    lines = [
        "# Auto-generated type hints for VppPapiProvider.",
        "# Generated by generate_python_stubs.py at build time.",
        "#",
        "# This .pyi stub makes basedpyright understand self.vapi",
        "# in test cases, which dynamically forwards to vpp_papi.",
        "",
        "from __future__ import annotations",
        "",
        "import datetime",
        "import ipaddress",
        "from collections.abc import Mapping, Sequence",
        "from typing import Any, Callable, NamedTuple",
        "",
    ]
    lines.extend(import_lines)
    lines.extend(
        [
            "class VppApiResult(NamedTuple):",
            '    """Base type for VAPI API results."""',
            "    retval: int",
            "",
            "",
            "class VppPapiProvider:",
            '    """Type hints for VppPapiProvider."""',
            "    vpp: Any",
            "    papi: Any",
            "    hook: Any",
            "    name: str",
            "    test_class: Any",
            "",
            "    def __init__(self, name: str, test_class: Any, read_timeout: int) -> None: ...",
            "    def __enter__(self) -> 'VppPapiProvider': ...",
            "    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...",
            "    def assert_negative_api_retval(self) -> 'VppPapiProvider': ...",
            "    def assert_zero_api_retval(self) -> 'VppPapiProvider': ...",
            "    def register_hook(self, hook: Any) -> None: ...",
            "    def collect_events(self) -> list: ...",
            "    def wait_for_event(self, timeout: float, name: str | None = ...) -> Any: ...",
            "    def connect(self) -> None: ...",
            "    def disconnect(self) -> None: ...",
            "    def cli(self, cli: str, strip_ansi_escapes: bool = ...) -> str: ...",
            "    def ppcli(self, cli: str) -> str: ...",
            "    def cli_return_response(self, cli: str) -> Any: ...",
            "    def api(self, api_fn: Any, api_args: Any, expected_retval: int = ...) -> Any: ...",
            "",
        ]
    )

    sorted_services = sorted(all_services, key=lambda s: s["name"])
    for svc in sorted_services:
        if svc["name"] in explicit_methods:
            continue
        method_line, _ = generate_method_signature(
            svc,
            typedef_union_names,
            enum_names,
            defaulted_params=defaultmapping.get(svc["name"]),
        )
        lines.append(method_line)
        lines.append("")

    stub_content = "\n".join(lines)

    with open(output_path, "w", encoding="UTF-8") as f:
        f.write(stub_content)

    print(
        f"Generated: {output_path} ({len(sorted_services)} methods, "
        f"{len(importable_types)} type imports)"
    )


def main():
    cliparser = argparse.ArgumentParser(
        description="Generate Python type stubs for vpp_papi"
    )
    cliparser.add_argument(
        "--srcdir",
        action="store",
        default=f"{BASE_DIR}/src",
        help="Source directory containing .api files",
    )
    cliparser.add_argument(
        "--output",
        action="store",
        help="Base output directory for generated files",
    )
    cliparser.add_argument(
        "--stubs-output",
        action="store",
        help="Directory for final stub files (vapi_types.py, provider.pyi)",
    )
    cliparser.add_argument(
        "--debug-target",
        action="store_true",
        default=False,
        help="Generate for debug build target",
    )

    args = cliparser.parse_args()

    src_dir = pathlib.Path(args.srcdir)

    # Determine output paths
    if args.debug_target:
        build_output = pathlib.Path(
            f"{BASE_DIR}/build-root/install-vpp_debug-native/vpp/share/vpp/api/"
        )
    else:
        build_output = pathlib.Path(
            f"{BASE_DIR}/build-root/install-vpp-native/vpp/share/vpp/api/"
        )

    if args.output:
        descriptor_dir = pathlib.Path(args.output)
    else:
        descriptor_dir = build_output

    # Create output subdirectories
    for d in OUTPUT_DIR_MAP.values():
        (descriptor_dir / d).mkdir(parents=True, exist_ok=True)

    # Find all .api files
    api_files = find_api_files(src_dir)
    print(f"Found {len(api_files)} .api files")

    if not api_files:
        print("No .api files found. Exiting.")
        sys.exit(1)

    # Step 1: Generate .python.json descriptors using vppapigen
    print("Generating Python descriptors...")
    for api_file in api_files:
        run_vppapigen_for_file(api_file, descriptor_dir, src_dir)

    # Step 2: Collect all descriptors
    descriptors = collect_descriptors(descriptor_dir)
    print(f"Collected {len(descriptors)} descriptors")

    if not descriptors:
        print("No descriptors generated. Exiting.")
        sys.exit(1)

    # Step 3: Generate final stub files
    # Determine stub output directory
    if args.stubs_output:
        stubs_dir = pathlib.Path(args.stubs_output)
    else:
        # Default: next to vpp_papi package
        stubs_dir = pathlib.Path(f"{BASE_DIR}/src/vpp-api/python/vpp_papi")

    stubs_dir.mkdir(parents=True, exist_ok=True)

    generate_vapi_types(descriptors, str(stubs_dir / "vapi_types.pyi"))

    # Also generate test framework stub. Parse the provider's defaultmapping
    # so methods with runtime-supplied defaults get `= ...` on those params.
    test_dir = pathlib.Path(f"{BASE_DIR}/test")
    defaultmapping = parse_defaultmapping(test_dir / "vpp_papi_provider.py")
    generate_provider_stub(
        descriptors,
        str(test_dir / "vpp_papi_provider.pyi"),
        defaultmapping=defaultmapping,
    )

    print("Done.")


if __name__ == "__main__":
    main()
