
package io.fd.vpp.jvpp.core.dto;

/**
 * <p>This class represents reply DTO.
 * <br>It was generated by dto_gen.py based on ['test.api.json']:
 * <pre>
 * [   [u'u16', u'_vl_msg_id'],
 *     [u'u32', u'context'],
 *     [u'i32', u'retval'],
 *     [u'u32', u'client_index'],
 *     [u'u32', u'vpe_pid'],
 *     {   u'crc': u'0xf6b0b8ca'}]
 * </pre>
 */
public final class ControlPingReply implements io.fd.vpp.jvpp.dto.JVppReply<io.fd.vpp.jvpp.core.dto.ControlPing> {
    public int context;
    public int clientIndex;
    public int vpePid;

    @Override
    @io.fd.vpp.jvpp.coverity.SuppressFBWarnings("UWF_UNWRITTEN_PUBLIC_OR_PROTECTED_FIELD")
    public int hashCode() {
        return java.util.Objects.hash(context, clientIndex, vpePid);
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        final ControlPingReply other = (ControlPingReply) o;

        if (!java.util.Objects.equals(this.context, other.context)) {
            return false;
        }
        if (!java.util.Objects.equals(this.clientIndex, other.clientIndex)) {
            return false;
        }
        if (!java.util.Objects.equals(this.vpePid, other.vpePid)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "ControlPingReply{"
            + "context=" + context + ", "
            + "clientIndex=" + clientIndex + ", "
            + "vpePid=" + vpePid + ", "
            + "}";
    }
}
