package io.fd.vpp.jvpp.core.callback;

/**
 * <p>Represents callback for plugin's api message.
 * <br>It was generated by jvpp_callback_gen.py based on ['test.api.json'].
 */
public interface FooDetailsCallback extends io.fd.vpp.jvpp.callback.JVppCallback {

    void onFooDetails(io.fd.vpp.jvpp.core.dto.FooDetails reply);
}
