
package io.fd.vpp.jvpp.core.dto;

/**
 * <p>This class represents request DTO.
 * <br>It was generated by dto_gen.py based on ['test.api.json']:
 * <pre>
 * [[u'u16', u'_vl_msg_id'], [u'u32', u'client_index'], [u'u32', u'context'], [u'u32', u'index'], {   u'crc': u'0x8ac76db6'}]
 * </pre>
 */
public final class FooDump implements io.fd.vpp.jvpp.dto.JVppRequest {
    public int index;

    @Override
    @io.fd.vpp.jvpp.coverity.SuppressFBWarnings("UWF_UNWRITTEN_PUBLIC_OR_PROTECTED_FIELD")
    public int hashCode() {
        return java.util.Objects.hash(index);
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        final FooDump other = (FooDump) o;

        if (!java.util.Objects.equals(this.index, other.index)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "FooDump{"
            + "index=" + index + ", "
            + "}";
    }

    @Override
    public int send(final io.fd.vpp.jvpp.JVpp jvpp) throws io.fd.vpp.jvpp.VppInvocationException {
        return ((io.fd.vpp.jvpp.core.JVppCore)jvpp).fooDump(this);
    }
}
