
package io.fd.vpp.jvpp.core.dto;

/**
 * <p>This class represents reply DTO.
 * <br>It was generated by dto_gen.py based on ['test.api.json']:
 * <pre>
 * [[u'u16', u'_vl_msg_id'], [u'u32', u'context'], [u'u32', u'index'], {   u'crc': u'0xe18f0c91'}]
 * </pre>
 */
public final class FooDetails implements io.fd.vpp.jvpp.dto.JVppReply<io.fd.vpp.jvpp.core.dto.FooDump> {
    public int context;
    public int index;

    @Override
    @io.fd.vpp.jvpp.coverity.SuppressFBWarnings("UWF_UNWRITTEN_PUBLIC_OR_PROTECTED_FIELD")
    public int hashCode() {
        return java.util.Objects.hash(context, index);
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        final FooDetails other = (FooDetails) o;

        if (!java.util.Objects.equals(this.context, other.context)) {
            return false;
        }
        if (!java.util.Objects.equals(this.index, other.index)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "FooDetails{"
            + "context=" + context + ", "
            + "index=" + index + ", "
            + "}";
    }
}
