
package io.fd.vpp.jvpp.core.dto;

/**
 * <p>This class represents reply DTO.
 * <br>It was generated by dto_gen.py based on // fixme msg.json_filename:
 * <pre>
{u'foo_request_reply': [[u'u16', u'_vl_msg_id'], [u'u32', u'context'], [u'i32', u'retval'], {u'crc': u'0xe8d4e804'}], u'foo_details': [[u'u16', u'_vl_msg_id'], [u'u32', u'context'], [u'u32', u'index'], {u'crc': u'0xe18f0c91'}], u'foo_request': [[u'u16', u'_vl_msg_id'], [u'u32', u'client_index'], [u'u32', u'context'], [u'u8', u'val_u8'], {u'crc': u'0x4199095a'}], u'foo_dump': [[u'u16', u'_vl_msg_id'], [u'u32', u'client_index'], [u'u32', u'context'], [u'u32', u'index'], {u'crc': u'0x8ac76db6'}]}
 * </pre>
 */
public final class FooRequestReply implements io.fd.vpp.jvpp.dto.JVppReply<io.fd.vpp.jvpp.core.dto.FooRequest> {

//fixme fields

//fixme hash_code

//fixme equals

//fixme to_string=

}
