package io.fd.vpp.jvpp.core;

/**
 * <p>Java representation of plugin's api file.
 * <br>It was generated by jvpp_java_ifc_gen.py based on ['test.api.json'].
 */
public interface JVppCore extends io.fd.vpp.jvpp.JVpp {
    /**
     * Generic dispatch method for sending requests to VPP
     *
     * @throws io.fd.vpp.jvpp.VppInvocationException if send request had failed
     */
    int send(io.fd.vpp.jvpp.dto.JVppRequest request) throws io.fd.vpp.jvpp.VppInvocationException;
    int requestNoArgs() throws io.fd.vpp.jvpp.VppInvocationException;
    int requestTwoArgs(io.fd.vpp.jvpp.core.dto.RequestTwoArgs request) throws io.fd.vpp.jvpp.VppInvocationException;
    int requestSingleArg(io.fd.vpp.jvpp.core.dto.RequestSingleArg request) throws io.fd.vpp.jvpp.VppInvocationException;
    int controlPing() throws io.fd.vpp.jvpp.VppInvocationException;
}
