package io.fd.vpp.jvpp.core.callback;

/**
 * <p>Represents callback for plugin's api message.
 * <br>It was generated by jvpp_callback_gen.py based on ['test.api.json'].
 */
public interface RequestNoArgsReplyCallback extends io.fd.vpp.jvpp.callback.JVppCallback {

    void onRequestNoArgsReply(io.fd.vpp.jvpp.core.dto.RequestNoArgsReply reply);
}
