
package io.fd.vpp.jvpp.core.dto;

/**
 * <p>This class represents reply DTO.
 * <br>It was generated by dto_gen.py based on // fixme msg.json_filename:
 * <pre>
 * [[u'u16', u'_vl_msg_id'], [u'u32', u'context'], [u'i32', u'retval'], {   u'crc': u'0xe8d4e804'}]
 * </pre>
 */
public final class RequestNoArgsReply implements io.fd.vpp.jvpp.dto.JVppReply<io.fd.vpp.jvpp.core.dto.RequestNoArgs> {
    public int retval;

    @Override
    @io.fd.vpp.jvpp.coverity.SuppressFBWarnings("UWF_UNWRITTEN_PUBLIC_OR_PROTECTED_FIELD")
    public int hashCode() {
        return java.util.Objects.hash(retval);
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        final RequestNoArgsReply other = (RequestNoArgsReply) o;

        if (!java.util.Objects.equals(this.retval, other.retval)) {
            return false;
        }

        return true;
    }

    @Override
    public String toString() {
        return "RequestNoArgsReply{"
            + "context=" + context + ", "
            + "}";
    }
}
