
package io.fd.vpp.jvpp.core.dto;

/**
 * <p>This class represents request DTO.
 * <br>It was generated by dto_gen.py based on // fixme msg.json_filename:
 * <pre>
 * [[u'u16', u'_vl_msg_id'], [u'u32', u'client_index'], [u'u32', u'context'], [u'u8', u'val_u8'], {   u'crc': u'0x4199095a'}]
 * </pre>
 */
public final class RequestSingleArg implements io.fd.vpp.jvpp.dto.JVppRequest {
    public byte valU8;

    @Override
    @io.fd.vpp.jvpp.coverity.SuppressFBWarnings("UWF_UNWRITTEN_PUBLIC_OR_PROTECTED_FIELD")
    public int hashCode() {
        return java.util.Objects.hash(valU8);
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        final RequestSingleArg other = (RequestSingleArg) o;

        if (!java.util.Objects.equals(this.valU8, other.valU8)) {
            return false;
        }

        return true;
    }

    @Override
    public String toString() {
        return "RequestSingleArg{"
            + "valU8=" + valU8 + ", "
            + "}";
    }

    @Override
    public int send(final io.fd.vpp.jvpp.JVpp jvpp) throws io.fd.vpp.jvpp.VppInvocationException {
        return ((io.fd.vpp.jvpp.core.JVppCore)jvpp).requestSingleArg(this);
    }
}
