
package io.fd.vpp.jvpp.core.dto;

/**
 * <p>This class represents reply DTO.
 * <br>It was generated by dto_gen.py based on // fixme msg.json_filename:
 * <pre>
 * [   [u'u16', u'_vl_msg_id'],
 *     [u'u32', u'client_index'],
 *     [u'u32', u'context'],
 *     [u'u8', u'val_i8'],
 *     [u'u8', u'val_u16'],
 *     {   u'crc': u'0x25ffac9b'}]
 * </pre>
 */
public final class RequestTwoArgsReply implements io.fd.vpp.jvpp.dto.JVppReply<io.fd.vpp.jvpp.core.dto.RequestTwoArgs> {
    public byte valI8;
    public byte valU16;

    @Override
    @io.fd.vpp.jvpp.coverity.SuppressFBWarnings("UWF_UNWRITTEN_PUBLIC_OR_PROTECTED_FIELD")
    public int hashCode() {
        return java.util.Objects.hash(valI8, valU16);
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        final RequestTwoArgsReply other = (RequestTwoArgsReply) o;

        if (!java.util.Objects.equals(this.valI8, other.valI8)) {
            return false;
        }
        if (!java.util.Objects.equals(this.valU16, other.valU16)) {
            return false;
        }

        return true;
    }

    @Override
    public String toString() {
        return "RequestTwoArgsReply{"
            + "clientIndex=" + clientIndex + ", "
            + "context=" + context + ", "
            + "valI8=" + valI8 + ", "
            + "valU16=" + valU16 + ", "
            + "}";
    }
}
