/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright (c) 2026 Cisco and/or its affiliates.
 */

/*
 * vlib_pool_cache: thread-owned fixed-size subpools.
 *
 * Backing storage is split into fixed-size vppinfra pools ("subpools"). A
 * returned u32 ID encodes the subpool index in the high bits and the element
 * slot in the low log2_subpool_size bits. Existing subpools never grow, so
 * pointers returned by elt_at_index remain stable when new subpools are
 * allocated.
 *
 * Each VPP thread owns the subpools it allocates from. Owner-thread alloc/free
 * mutates the fixed pool directly and does not take the shared lock. A
 * different thread freeing an element never mutates the owner's fixed pool;
 * instead it publishes the slot to an intrusive remote-free stack in the
 * subpool metadata. The owner drains those remote frees on allocation paths.
 *
 * Usage:
 *
 *   1. Drop the instantiation macro at file scope in a .c:
 *
 *        VLIB_POOL_CACHE_DEFINE (flow, vnet_flow_t) = {
 *          .name = "flow",
 *        };
 *
 *      The registration is a template for every cache initialized from this
 *      declaration. That generates:
 *        - flow_pool_cache_t            (typed wrapper struct)
 *        - flow_pool_cache_init         (constructor; registers one instance)
 *        - flow_pool_cache_free_resources
 *        - flow_pool_cache_alloc        (returns u32 index)
 *        - flow_pool_cache_free         (push index back)
 *        - flow_pool_cache_elt_at_index (idx -> T *)
 *        - flow_pool_cache_is_free_index
 *
 *   2. Embed the typed wrapper in your main struct and init it:
 *
 *        typedef struct {
 *          flow_pool_cache_t flows;   // owns the backing pool
 *          ...
 *        } my_main_t;
 *
 *        flow_pool_cache_init (&mm->flows, "flow-instance", 0,
 *                              CLIB_CACHE_LINE_BYTES);
 *
 *   3. Use the typed API:
 *
 *        u32 idx = flow_pool_cache_alloc (&mm->flows);
 *        vnet_flow_t *f = flow_pool_cache_elt_at_index (&mm->flows, idx);
 *        ...
 *        flow_pool_cache_free (&mm->flows, idx);
 *
 * Notes:
 * - The only sizing knob is log2_subpool_size. Pass 0 for the default.
 * - Same-owner alloc/free is lock-free after the owner has a partial subpool.
 * - Empty subpools are kept for reuse. Reclamation is intentionally separate.
 * - Alignment is the byte alignment used when each fixed subpool is created.
 *   Pass 0 for natural alignment, or e.g. CLIB_CACHE_LINE_BYTES.
 * - The registration name is the default instance name. Pass NULL to init to
 *   use it, or pass a per-instance name for CLI matching.
 */

#ifndef included_vlib_pool_cache_h
#define included_vlib_pool_cache_h

#include <vlib/vlib.h>
#include <vppinfra/atomics.h>
#include <vppinfra/cache.h>
#include <vppinfra/lock.h>
#include <vppinfra/pool.h>
#include <vppinfra/vec.h>

#define VLIB_POOL_CACHE_DEFAULT_LOG2_SUBPOOL_SIZE   12
#define VLIB_POOL_CACHE_LOG2_SUBPOOL_PTR_CHUNK_SIZE 12
#define VLIB_POOL_CACHE_SUBPOOL_PTR_CHUNK_SIZE	    (1U << VLIB_POOL_CACHE_LOG2_SUBPOOL_PTR_CHUNK_SIZE)
#define VLIB_POOL_CACHE_SUBPOOL_PTR_CHUNK_MASK	    (VLIB_POOL_CACHE_SUBPOOL_PTR_CHUNK_SIZE - 1)
#define VLIB_POOL_CACHE_INVALID_INDEX		    ((u32) ~0)
#define VLIB_POOL_CACHE_INVALID_THREAD_INDEX	    ((u32) ~0)

#define foreach_cache_slot_state                                                                   \
  _ (FREE, 0)                                                                                      \
  _ (ALLOCATED, 1)                                                                                 \
  _ (REMOTE_PENDING, 2)

typedef enum
{
#define _(n, v) VLIB_POOL_CACHE_SLOT_##n = (v),
  foreach_cache_slot_state
#undef _
} vlib_pool_cache_slot_state_t;

typedef struct
{
  CLIB_CACHE_LINE_ALIGN_MARK (cacheline0);
  u32 current_subpool;	       /* head of owned subpools with free slots */
  u32 remote_pending_subpools; /* atomic stack of subpools to drain */
} vlib_pool_cache_thread_t;

typedef struct
{
  CLIB_CACHE_LINE_ALIGN_MARK (cacheline0);
  u8 *slot_state;
  u32 *remote_next;
  u32 owner_thread_index;
  u32 owner_next;
  u32 global_next;
  u32 remote_pending_next;
  u32 remote_head;
  u8 on_owner_free_list;
} vlib_pool_cache_subpool_meta_t;

typedef struct vlib_pool_cache_registration_t_ vlib_pool_cache_registration_t;

/*
 * Type-agnostic state common to every pool_cache instance. Embedded by
 * value in the typed wrapper struct generated by VLIB_POOL_CACHE_DEFINE;
 * not used directly by callers.
 */
typedef struct vlib_pool_cache_t_
{
  /* Instance diagnostics. Registration is the typed template for this cache. */
  char *name;
  vlib_pool_cache_registration_t *registration;
  struct vlib_pool_cache_t_ *next_instance;

  /* Serializes subpool creation and the global empty-subpool depot. */
  clib_spinlock_t lock;

  /* Per-thread ownership state, indexed by vlib_get_thread_index(). */
  vlib_pool_cache_thread_t *per_thread;

  /* Stable chunked metadata table. */
  vlib_pool_cache_subpool_meta_t **subpool_meta_chunks;

  /* Global stack of empty, unowned subpools. Guarded by lock. */
  u32 empty_subpools;

  /* Subpool index geometry. */
  u32 log2_subpool_size;
  u32 subpool_size;
  u32 subpool_mask;
  u32 max_subpools;
  u32 max_subpool_chunks;
  u32 n_subpools;

  /* Byte alignment used when fixed subpools are created. */
  u32 align;

} vlib_pool_cache_t;

struct vlib_pool_cache_registration_t_
{
  char *name;
  format_function_t *format_element;
  struct vlib_pool_cache_registration_t_ *next_registration;
};

typedef struct
{
  vlib_pool_cache_registration_t *registrations;
  vlib_pool_cache_t *instances;
} vlib_pool_cache_main_t;

extern vlib_pool_cache_main_t vlib_pool_cache_main;

void vlib_pool_cache_init_state (vlib_pool_cache_t *c, u32 log2_subpool_size, u32 align);
void vlib_pool_cache_free_state (vlib_pool_cache_t *c);
void vlib_pool_cache_register_instance (vlib_pool_cache_t *c,
					vlib_pool_cache_registration_t *registration, char *name);
void vlib_pool_cache_unregister_instance (vlib_pool_cache_t *c);
u8 *format_vlib_pool_cache (u8 *s, va_list *args);

/* Compose a public encoded ID from a subpool index and slot index. */
static_always_inline u32
vlib_pool_cache_encode_index (const vlib_pool_cache_t *c, u32 subpool_index, u32 elt_index)
{
  ASSERT (subpool_index < c->max_subpools);
  ASSERT (elt_index < c->subpool_size);
  return (u32) (((u64) subpool_index << c->log2_subpool_size) | elt_index);
}

/* Extract the subpool index from a public encoded ID. */
static_always_inline u32
vlib_pool_cache_subpool_index (const vlib_pool_cache_t *c, u32 index)
{
  return index >> c->log2_subpool_size;
}

/* Extract the slot index within a subpool from a public encoded ID. */
static_always_inline u32
vlib_pool_cache_elt_index (const vlib_pool_cache_t *c, u32 index)
{
  return index & c->subpool_mask;
}

/* Return/create the metadata-table chunk that contains a subpool slot. */
static_always_inline vlib_pool_cache_subpool_meta_t *
vlib_pool_cache_get_subpool_meta_chunk (vlib_pool_cache_t *c, u32 pidx)
{
  u32 chunk_index = pidx >> VLIB_POOL_CACHE_LOG2_SUBPOOL_PTR_CHUNK_SIZE;
  vlib_pool_cache_subpool_meta_t *chunk = c->subpool_meta_chunks[chunk_index];

  if (PREDICT_FALSE (chunk == 0))
    {
      /* Metadata chunks are allocated lazily just like typed pool-pointer
       * chunks. Existing chunks never move, so subpool metadata pointers stay
       * stable after publication. */
      vec_validate_aligned (chunk, VLIB_POOL_CACHE_SUBPOOL_PTR_CHUNK_SIZE - 1,
			    CLIB_CACHE_LINE_BYTES);
      c->subpool_meta_chunks[chunk_index] = chunk;
    }

  return chunk;
}

/* Resolve a subpool index to its stable metadata entry. */
static_always_inline vlib_pool_cache_subpool_meta_t *
vlib_pool_cache_subpool_meta_at (vlib_pool_cache_t *c, u32 pidx)
{
  vlib_pool_cache_subpool_meta_t *chunk;

  ASSERT (pidx < clib_atomic_load_acq_n (&c->n_subpools));
  chunk = c->subpool_meta_chunks[pidx >> VLIB_POOL_CACHE_LOG2_SUBPOOL_PTR_CHUNK_SIZE];
  ASSERT (chunk != 0);
  return chunk + (pidx & VLIB_POOL_CACHE_SUBPOOL_PTR_CHUNK_MASK);
}

/* Queue a subpool on its owner's pending remote-free stack. */
static_always_inline void
vlib_pool_cache_enqueue_remote_pending (vlib_pool_cache_t *c, u32 owner_thread_index, u32 pidx)
{
  vlib_pool_cache_subpool_meta_t *sp;
  vlib_pool_cache_thread_t *pt;
  u32 old_head;

  ASSERT (owner_thread_index < vec_len (c->per_thread));
  sp = vlib_pool_cache_subpool_meta_at (c, pidx);

  /* remote_head provides the edge trigger: only remote frees that change the
   * subpool from empty to non-empty queue it here. Later remote frees only push
   * slots to remote_head, and the owner drains the whole stack when it processes
   * this one pending-list entry. */
  pt = vec_elt_at_index (c->per_thread, owner_thread_index);
  do
    {
      old_head = __atomic_load_n (&pt->remote_pending_subpools, __ATOMIC_RELAXED);
      sp->remote_pending_next = old_head;
    }
  while (!__atomic_compare_exchange_n (&pt->remote_pending_subpools, &old_head, pidx, 0,
				       __ATOMIC_RELEASE, __ATOMIC_RELAXED));
}

/*
 * VLIB_POOL_CACHE_DEFINE(NAME, T)
 *
 * Generate a typed wrapper around fixed subpools of T. Drop one of these at
 * file scope. NAME is a caller-chosen prefix used for the generated struct and
 * functions; T is the pool element type. The macro expands to a registration
 * declaration as its final statement, so callers fill registration fields with
 * an initializer:
 *
 *   VLIB_POOL_CACHE_DEFINE (flow, vnet_flow_t) = {
 *     .name = "flow",
 *     .format_element = format_flow_element,
 *   };
 *
 *   static u8 *
 *   format_flow_element (u8 *s, vnet_flow_t *f)
 *   {
 *     return format (s, "%U", format_vnet_flow, f);
 *   }
 *
 * Generated symbols (all static_always_inline so each TU gets a copy and
 * the optimizer can fully inline the fast path):
 *
 *   typedef struct { ... } NAME##_pool_cache_t;
 *   NAME##_pool_cache_t *NAME##_pool_cache_from_state (vlib_pool_cache_t *c);
 *   void NAME##_pool_cache_init        (NAME##_pool_cache_t *c,
 *                                       char *name, u32 log2_subpool_size,
 *                                       u32 align);
 *   void NAME##_pool_cache_free_resources (NAME##_pool_cache_t *c);
 *   u32  NAME##_pool_cache_alloc       (NAME##_pool_cache_t *c);
 *   void NAME##_pool_cache_free        (NAME##_pool_cache_t *c, u32 idx);
 *   T *  NAME##_pool_cache_elt_at_index(NAME##_pool_cache_t *c, u32 idx);
 *   int  NAME##_pool_cache_is_free_index (NAME##_pool_cache_t *c, u32 idx);
 *
 */
#define VLIB_POOL_CACHE_DEFINE(NAME, T)                                                            \
                                                                                                   \
  static vlib_pool_cache_registration_t NAME##_pool_cache_registration;                            \
                                                                                                   \
  static void __vlib_add_pool_cache_registration_##NAME (void) __attribute__ ((__constructor__));  \
  static void __vlib_add_pool_cache_registration_##NAME (void)                                     \
  {                                                                                                \
    vlib_pool_cache_main_t *_pcm_ = &vlib_pool_cache_main;                                         \
    NAME##_pool_cache_registration.next_registration = _pcm_->registrations;                       \
    _pcm_->registrations = &NAME##_pool_cache_registration;                                        \
  }                                                                                                \
                                                                                                   \
  static void __vlib_rm_pool_cache_registration_##NAME (void) __attribute__ ((__destructor__));    \
  static void __vlib_rm_pool_cache_registration_##NAME (void)                                      \
  {                                                                                                \
    vlib_pool_cache_main_t *_pcm_ = &vlib_pool_cache_main;                                         \
    VLIB_REMOVE_FROM_LINKED_LIST (_pcm_->registrations, &NAME##_pool_cache_registration,           \
				  next_registration);                                              \
  }                                                                                                \
                                                                                                   \
  /* Typed wrapper. _pool_chunks is private to the generated accessors. */                         \
  typedef struct                                                                                   \
  {                                                                                                \
    T ***_pool_chunks;                                                                             \
    vlib_pool_cache_t state;                                                                       \
  } NAME##_pool_cache_t;                                                                           \
                                                                                                   \
  /* Return/create the pointer-table chunk that contains a subpool slot. */                        \
  static_always_inline T **NAME##_pool_cache_get_pool_chunk_ (NAME##_pool_cache_t *_c_,            \
							      u32 _pidx_)                          \
  {                                                                                                \
    u32 _chunk_index_ = _pidx_ >> VLIB_POOL_CACHE_LOG2_SUBPOOL_PTR_CHUNK_SIZE;                     \
    T **_chunk_ = _c_->_pool_chunks[_chunk_index_];                                                \
    if (PREDICT_FALSE (_chunk_ == 0))                                                              \
      {                                                                                            \
	/* The outer vector may move, so it stores pointers to fixed chunks. Once a                \
	 * chunk exists, the subpool pointers inside that chunk stay at stable addresses. */       \
	vec_validate_aligned (_chunk_, VLIB_POOL_CACHE_SUBPOOL_PTR_CHUNK_SIZE - 1,                 \
			      CLIB_CACHE_LINE_BYTES);                                              \
	_c_->_pool_chunks[_chunk_index_] = _chunk_;                                                \
      }                                                                                            \
    return _chunk_;                                                                                \
  }                                                                                                \
                                                                                                   \
  /* Resolve a subpool index to a fixed-size backing pool pointer. */                              \
  static_always_inline T *NAME##_pool_cache_pool_at_ (NAME##_pool_cache_t *_c_, u32 _pidx_)        \
  {                                                                                                \
    T **_chunk_;                                                                                   \
    /* n_subpools is released only after both the typed pool pointer and its                       \
     * metadata have been initialized, so this acquire protects readers of a public ID. */         \
    ASSERT (_pidx_ < clib_atomic_load_acq_n (&_c_->state.n_subpools));                             \
    _chunk_ = _c_->_pool_chunks[_pidx_ >> VLIB_POOL_CACHE_LOG2_SUBPOOL_PTR_CHUNK_SIZE];            \
    ASSERT (_chunk_ != 0);                                                                         \
    return _chunk_[_pidx_ & VLIB_POOL_CACHE_SUBPOOL_PTR_CHUNK_MASK];                               \
  }                                                                                                \
                                                                                                   \
  /* Add a subpool to the calling owner's partial-subpool list. */                                 \
  static_always_inline void NAME##_pool_cache_owner_add_free_ (                                    \
    NAME##_pool_cache_t *_c_, vlib_pool_cache_thread_t *_pt_, u32 _pidx_)                          \
  {                                                                                                \
    vlib_pool_cache_subpool_meta_t *_sp_ = vlib_pool_cache_subpool_meta_at (&_c_->state, _pidx_);  \
    /* This list is owned by the calling thread. It contains subpools with at                      \
     * least one local free slot, so allocation can just use the head. */                          \
    if (PREDICT_FALSE (_sp_->on_owner_free_list))                                                  \
      return;                                                                                      \
    /* Head insertion keeps allocation cheap: alloc only has to look at                            \
     * pt->current_subpool, and only this owner thread mutates owner_next. */                      \
    _sp_->owner_next = _pt_->current_subpool;                                                      \
    _pt_->current_subpool = _pidx_;                                                                \
    _sp_->on_owner_free_list = 1;                                                                  \
  }                                                                                                \
                                                                                                   \
  /* Remove a subpool from the calling owner's partial-subpool list. */                            \
  static_always_inline void NAME##_pool_cache_owner_remove_free_ (                                 \
    NAME##_pool_cache_t *_c_, vlib_pool_cache_thread_t *_pt_, u32 _pidx_)                          \
  {                                                                                                \
    vlib_pool_cache_subpool_meta_t *_sp_ = vlib_pool_cache_subpool_meta_at (&_c_->state, _pidx_);  \
    vlib_pool_cache_subpool_meta_t *_prev_sp_;                                                     \
    u32 _prev_;                                                                                    \
    /* Subpools leave this owner-local list when they become full or empty.                        \
     * This is not the hot allocation operation, so an intrusive singly-linked                     \
     * list is enough and avoids extra per-thread vectors. */                                      \
    if (PREDICT_FALSE (!_sp_->on_owner_free_list))                                                 \
      return;                                                                                      \
    if (_pt_->current_subpool == _pidx_)                                                           \
      _pt_->current_subpool = _sp_->owner_next;                                                    \
    else                                                                                           \
      {                                                                                            \
	for (_prev_ = _pt_->current_subpool; _prev_ != VLIB_POOL_CACHE_INVALID_INDEX;              \
	     _prev_ = _prev_sp_->owner_next)                                                       \
	  {                                                                                        \
	    _prev_sp_ = vlib_pool_cache_subpool_meta_at (&_c_->state, _prev_);                     \
	    /* There should be at most one list entry because owner_add_free_ is guarded           \
	     * by on_owner_free_list. Stop as soon as the predecessor is found. */                 \
	    if (_prev_sp_->owner_next == _pidx_)                                                   \
	      {                                                                                    \
		_prev_sp_->owner_next = _sp_->owner_next;                                          \
		break;                                                                             \
	      }                                                                                    \
	  }                                                                                        \
      }                                                                                            \
    _sp_->owner_next = VLIB_POOL_CACHE_INVALID_INDEX;                                              \
    _sp_->on_owner_free_list = 0;                                                                  \
  }                                                                                                \
                                                                                                   \
  /* Publish an empty owned subpool to the global empty depot. */                                  \
  static_always_inline void NAME##_pool_cache_release_empty_ (                                     \
    NAME##_pool_cache_t *_c_, vlib_pool_cache_thread_t *_pt_, u32 _pidx_)                          \
  {                                                                                                \
    vlib_pool_cache_subpool_meta_t *_sp_ = vlib_pool_cache_subpool_meta_at (&_c_->state, _pidx_);  \
    /* The owner is the only thread that can prove the subpool is empty: local                     \
     * frees mutate the fixed pool directly, and remote frees are first drained                    \
     * into that same fixed pool by the owner. */                                                  \
    NAME##_pool_cache_owner_remove_free_ (_c_, _pt_, _pidx_);                                      \
    clib_spinlock_lock (&_c_->state.lock);                                                         \
    /* Clear ownership before linking into the global empty depot. From here until a               \
     * new owner is installed by claim_empty_locked_, no valid remote free should target           \
     * this subpool because an empty pool has no live encoded IDs left. */                         \
    clib_atomic_store_rel_n (&_sp_->owner_thread_index, VLIB_POOL_CACHE_INVALID_THREAD_INDEX);     \
    _sp_->global_next = _c_->state.empty_subpools;                                                 \
    _c_->state.empty_subpools = _pidx_;                                                            \
    clib_spinlock_unlock (&_c_->state.lock);                                                       \
  }                                                                                                \
                                                                                                   \
  /* Append, initialize, and assign one fixed-size subpool to an owner. */                         \
  static_always_inline void NAME##_pool_cache_add_subpool_locked_ (                                \
    NAME##_pool_cache_t *_c_, vlib_pool_cache_thread_t *_pt_, u32 _thread_index_)                  \
  {                                                                                                \
    T *_pool_ = 0;                                                                                 \
    T **_pool_chunk_;                                                                              \
    vlib_pool_cache_subpool_meta_t *_meta_chunk_;                                                  \
    vlib_pool_cache_subpool_meta_t *_sp_;                                                          \
    u32 _i_, _pidx_ = _c_->state.n_subpools;                                                       \
    if (PREDICT_FALSE (_pidx_ >= _c_->state.max_subpools))                                         \
      clib_panic ("pool cache '%s' exhausted u32 index space",                                     \
		  _c_->state.name ? _c_->state.name : NAME##_pool_cache_registration.name);        \
    /* Create a fixed-capacity vppinfra pool for this subpool. This pool is never                  \
     * grown after publication, which is what keeps elt_at_index pointers stable. */               \
    _pool_init_fixed ((void **) &_pool_, _vec_elt_sz (_pool_), _c_->state.subpool_size,            \
		      _vec_align (_pool_, _c_->state.align));                                      \
    /* Publish the typed storage and its generic metadata at the same subpool                      \
     * index. The public u32 index is only valid after n_subpools is released. */                  \
    _pool_chunk_ = NAME##_pool_cache_get_pool_chunk_ (_c_, _pidx_);                                \
    _pool_chunk_[_pidx_ & VLIB_POOL_CACHE_SUBPOOL_PTR_CHUNK_MASK] = _pool_;                        \
    _meta_chunk_ = vlib_pool_cache_get_subpool_meta_chunk (&_c_->state, _pidx_);                   \
    _sp_ = _meta_chunk_ + (_pidx_ & VLIB_POOL_CACHE_SUBPOOL_PTR_CHUNK_MASK);                       \
    clib_memset (_sp_, 0, sizeof (*_sp_));                                                         \
    _sp_->owner_thread_index = _thread_index_;                                                     \
    _sp_->owner_next = VLIB_POOL_CACHE_INVALID_INDEX;                                              \
    _sp_->global_next = VLIB_POOL_CACHE_INVALID_INDEX;                                             \
    _sp_->remote_pending_next = VLIB_POOL_CACHE_INVALID_INDEX;                                     \
    _sp_->remote_head = VLIB_POOL_CACHE_INVALID_INDEX;                                             \
    /* remote_next is the intrusive link storage for remote frees. Its                             \
     * capacity is exactly the subpool size, so remote free does not allocate. */                  \
    vec_validate_aligned (_sp_->remote_next, _c_->state.subpool_size - 1, CLIB_CACHE_LINE_BYTES);  \
    vec_validate_aligned (_sp_->slot_state, _c_->state.subpool_size - 1, CLIB_CACHE_LINE_BYTES);   \
    for (_i_ = 0; _i_ < _c_->state.subpool_size; _i_++)                                            \
      {                                                                                            \
	_sp_->remote_next[_i_] = VLIB_POOL_CACHE_INVALID_INDEX;                                    \
	_sp_->slot_state[_i_] = VLIB_POOL_CACHE_SLOT_FREE;                                         \
      }                                                                                            \
    /* Make the subpool visible after all typed storage, metadata, and remote-free                 \
     * link slots are initialized. Readers acquire-load n_subpools before resolving it. */         \
    clib_atomic_store_rel_n (&_c_->state.n_subpools, _pidx_ + 1);                                  \
    NAME##_pool_cache_owner_add_free_ (_c_, _pt_, _pidx_);                                         \
  }                                                                                                \
                                                                                                   \
  /* Claim an empty subpool from the global depot for the calling owner. */                        \
  static_always_inline void NAME##_pool_cache_claim_empty_locked_ (                                \
    NAME##_pool_cache_t *_c_, vlib_pool_cache_thread_t *_pt_, u32 _thread_index_)                  \
  {                                                                                                \
    vlib_pool_cache_subpool_meta_t *_sp_;                                                          \
    u32 _pidx_ = _c_->state.empty_subpools;                                                        \
    /* The global depot contains fully-empty unowned subpools. Reusing one is                      \
     * cheaper than allocating a fresh fixed pool, but both happen only here. */                   \
    if (PREDICT_FALSE (_pidx_ == VLIB_POOL_CACHE_INVALID_INDEX))                                   \
      {                                                                                            \
	NAME##_pool_cache_add_subpool_locked_ (_c_, _pt_, _thread_index_);                         \
	return;                                                                                    \
      }                                                                                            \
    _sp_ = vlib_pool_cache_subpool_meta_at (&_c_->state, _pidx_);                                  \
    /* Pop the empty depot while holding the global lock. The subpool remains empty;               \
     * only the owner_thread_index and owner-local list membership change here. */                 \
    _c_->state.empty_subpools = _sp_->global_next;                                                 \
    _sp_->global_next = VLIB_POOL_CACHE_INVALID_INDEX;                                             \
    clib_atomic_store_rel_n (&_sp_->owner_thread_index, _thread_index_);                           \
    NAME##_pool_cache_owner_add_free_ (_c_, _pt_, _pidx_);                                         \
  }                                                                                                \
                                                                                                   \
  /* Drain one owned subpool's intrusive remote-free stack. */                                     \
  static_always_inline void NAME##_pool_cache_drain_remote_subpool_ (                              \
    NAME##_pool_cache_t *_c_, vlib_pool_cache_thread_t *_pt_, u32 _thread_index_, u32 _pidx_)      \
  {                                                                                                \
    vlib_pool_cache_subpool_meta_t *_sp_ = vlib_pool_cache_subpool_meta_at (&_c_->state, _pidx_);  \
    T *_pool_ = NAME##_pool_cache_pool_at_ (_c_, _pidx_);                                          \
    u32 _head_, _next_;                                                                            \
    /* Take the whole remote stack in one atomic operation. Non-owner frees                        \
     * can keep pushing onto the now-empty head while the owner applies this batch. */             \
    _head_ =                                                                                       \
      __atomic_exchange_n (&_sp_->remote_head, VLIB_POOL_CACHE_INVALID_INDEX, __ATOMIC_ACQ_REL);   \
    while (_head_ != VLIB_POOL_CACHE_INVALID_INDEX)                                                \
      {                                                                                            \
	_next_ = _sp_->remote_next[_head_];                                                        \
	_sp_->remote_next[_head_] = VLIB_POOL_CACHE_INVALID_INDEX;                                 \
	/* Convert the remote stack entry back into normal pool state. Only the owner              \
	 * calls pool_put_index, so vppinfra pool state remains single-writer even when            \
	 * frees originate from other workers. */                                                  \
	pool_put_index (_pool_, _head_);                                                           \
	clib_atomic_store_rel_n (&_sp_->slot_state[_head_], VLIB_POOL_CACHE_SLOT_FREE);            \
	_head_ = _next_;                                                                           \
      }                                                                                            \
    /* If a remote free arrives after the swap above, it observes an empty                         \
     * remote_head, pushes its slot, and queues this subpool again. */                             \
    /* Remote frees may have changed the local occupancy. Keep this subpool on the                 \
     * owner's partial list if it has space, or hand it to the empty depot if fully free. */       \
    if (pool_elts (_pool_) == 0)                                                                   \
      NAME##_pool_cache_release_empty_ (_c_, _pt_, _pidx_);                                        \
    else if (pool_free_elts (_pool_) > 0)                                                          \
      NAME##_pool_cache_owner_add_free_ (_c_, _pt_, _pidx_);                                       \
  }                                                                                                \
                                                                                                   \
  /* Drain all pending remote-free subpools for the calling owner. */                              \
  static_always_inline void NAME##_pool_cache_drain_remote_ (                                      \
    NAME##_pool_cache_t *_c_, vlib_pool_cache_thread_t *_pt_, u32 _thread_index_)                  \
  {                                                                                                \
    u32 _pidx_, _next_;                                                                            \
    _pidx_ =                                                                                       \
      clib_atomic_swap_acq_n (&_pt_->remote_pending_subpools, VLIB_POOL_CACHE_INVALID_INDEX);      \
    /* Detach the whole pending list so remote freers can immediately start a new list             \
     * while the owner drains the snapshot below. Each subpool appears at most once on             \
     * this list; draining may requeue it if a remote free races with the owner batch. */          \
    while (_pidx_ != VLIB_POOL_CACHE_INVALID_INDEX)                                                \
      {                                                                                            \
	vlib_pool_cache_subpool_meta_t *_sp_ =                                                     \
	  vlib_pool_cache_subpool_meta_at (&_c_->state, _pidx_);                                   \
	_next_ = _sp_->remote_pending_next;                                                        \
	NAME##_pool_cache_drain_remote_subpool_ (_c_, _pt_, _thread_index_, _pidx_);               \
	_pidx_ = _next_;                                                                           \
      }                                                                                            \
  }                                                                                                \
                                                                                                   \
  /* Slow path: drain remote frees or claim/create a partial owned subpool. */                     \
  static_always_inline void NAME##_pool_cache_alloc_slow_ (                                        \
    NAME##_pool_cache_t *_c_, vlib_pool_cache_thread_t *_pt_, u32 _thread_index_)                  \
  {                                                                                                \
    /* Prefer reclaiming remote frees first; that keeps ownership stable and                       \
     * avoids taking the global lock when remote frees made an owned subpool usable. */            \
    NAME##_pool_cache_drain_remote_ (_c_, _pt_, _thread_index_);                                   \
    if (PREDICT_TRUE (_pt_->current_subpool != VLIB_POOL_CACHE_INVALID_INDEX))                     \
      return;                                                                                      \
    clib_spinlock_lock (&_c_->state.lock);                                                         \
    NAME##_pool_cache_claim_empty_locked_ (_c_, _pt_, _thread_index_);                             \
    clib_spinlock_unlock (&_c_->state.lock);                                                       \
  }                                                                                                \
                                                                                                   \
  /* Publish a non-owner free to the subpool's intrusive remote-free stack. */                     \
  static_always_inline int NAME##_pool_cache_remote_free_ (NAME##_pool_cache_t *_c_, u32 _pidx_,   \
							   u32 _elt_index_)                        \
  {                                                                                                \
    vlib_pool_cache_subpool_meta_t *_sp_ = vlib_pool_cache_subpool_meta_at (&_c_->state, _pidx_);  \
    u32 _owner_, _old_head_;                                                                       \
    u8 _expected_ = VLIB_POOL_CACHE_SLOT_ALLOCATED;                                                \
    if (!__atomic_compare_exchange_n (&_sp_->slot_state[_elt_index_], &_expected_,                 \
				      VLIB_POOL_CACHE_SLOT_REMOTE_PENDING, 0, __ATOMIC_ACQ_REL,    \
				      __ATOMIC_RELAXED))                                           \
      return 0;                                                                                    \
    _owner_ = clib_atomic_load_acq_n (&_sp_->owner_thread_index);                                  \
    if (PREDICT_FALSE (_owner_ == VLIB_POOL_CACHE_INVALID_THREAD_INDEX))                           \
      {                                                                                            \
	clib_atomic_store_rel_n (&_sp_->slot_state[_elt_index_], VLIB_POOL_CACHE_SLOT_ALLOCATED);  \
	ASSERT (_owner_ != VLIB_POOL_CACHE_INVALID_THREAD_INDEX);                                  \
	return 0;                                                                                  \
      }                                                                                            \
    /* Remote free publishes only a slot index. It does not touch the typed                        \
     * element pool or any owner-local list state. */                                              \
    do                                                                                             \
      {                                                                                            \
	_old_head_ = clib_atomic_load_acq_n (&_sp_->remote_head);                                  \
	_sp_->remote_next[_elt_index_] = _old_head_;                                               \
      }                                                                                            \
    while (!__atomic_compare_exchange_n (&_sp_->remote_head, &_old_head_, _elt_index_, 0,          \
					 __ATOMIC_RELEASE, __ATOMIC_RELAXED));                     \
    if (_old_head_ == VLIB_POOL_CACHE_INVALID_INDEX)                                               \
      vlib_pool_cache_enqueue_remote_pending (&_c_->state, _owner_, _pidx_);                       \
    return 1;                                                                                      \
  }                                                                                                \
                                                                                                   \
  /* Construct an empty cache. Backing subpools grow lazily on alloc slow paths. */                \
  static_always_inline void NAME##_pool_cache_init (NAME##_pool_cache_t *_c_, char *_name_,        \
						    u32 _log2_subpool_size_, u32 _align_)          \
  {                                                                                                \
    _c_->_pool_chunks = 0;                                                                         \
    vlib_pool_cache_init_state (&_c_->state, _log2_subpool_size_, _align_);                        \
    vlib_pool_cache_register_instance (&_c_->state, &NAME##_pool_cache_registration, _name_);      \
    vec_validate_aligned (_c_->_pool_chunks, _c_->state.max_subpool_chunks - 1,                    \
			  CLIB_CACHE_LINE_BYTES);                                                  \
  }                                                                                                \
                                                                                                   \
  /* Release backing pools and metadata. Caller must ensure workers are idle. */                   \
  static_always_inline void NAME##_pool_cache_free_resources (NAME##_pool_cache_t *_c_)            \
  {                                                                                                \
    u32 _i_;                                                                                       \
    vlib_pool_cache_unregister_instance (&_c_->state);                                             \
    for (_i_ = 0; _i_ < _c_->state.n_subpools; _i_++)                                              \
      {                                                                                            \
	T *_pool_ = NAME##_pool_cache_pool_at_ (_c_, _i_);                                         \
	pool_free (_pool_);                                                                        \
      }                                                                                            \
    for (_i_ = 0; _i_ < vec_len (_c_->_pool_chunks); _i_++)                                        \
      vec_free (_c_->_pool_chunks[_i_]);                                                           \
    vec_free (_c_->_pool_chunks);                                                                  \
    vlib_pool_cache_free_state (&_c_->state);                                                      \
  }                                                                                                \
                                                                                                   \
  /* Resolve an encoded ID to its element pointer. */                                              \
  static_always_inline T *NAME##_pool_cache_elt_at_index (NAME##_pool_cache_t *_c_, u32 _idx_)     \
  {                                                                                                \
    u32 _pidx_ = vlib_pool_cache_subpool_index (&_c_->state, _idx_);                               \
    u32 _elt_index_ = vlib_pool_cache_elt_index (&_c_->state, _idx_);                              \
    T *_pool_ = NAME##_pool_cache_pool_at_ (_c_, _pidx_);                                          \
    return pool_elt_at_index (_pool_, _elt_index_);                                                \
  }                                                                                                \
                                                                                                   \
  static_always_inline __clib_unused u8 *NAME##_pool_cache_format_element (                        \
    u8 *s, NAME##_pool_cache_t *_c_, u32 _idx_)                                                    \
  {                                                                                                \
    format_function_t *_f_ = NAME##_pool_cache_registration.format_element;                        \
    if (_f_ == 0)                                                                                  \
      return s;                                                                                    \
    return format (s, "%U", _f_, NAME##_pool_cache_elt_at_index (_c_, _idx_));                     \
  }                                                                                                \
                                                                                                   \
  /* Test whether a pool index is locally free or pending remote free. This helper                 \
   * reads pool-cache slot state, not the backing vppinfra pool freelist. */                       \
  static_always_inline int NAME##_pool_cache_is_free_index (NAME##_pool_cache_t *_c_, u32 _idx_)   \
  {                                                                                                \
    u32 _pidx_ = vlib_pool_cache_subpool_index (&_c_->state, _idx_);                               \
    u32 _elt_index_ = vlib_pool_cache_elt_index (&_c_->state, _idx_);                              \
    vlib_pool_cache_subpool_meta_t *_sp_;                                                          \
    if (PREDICT_FALSE (_pidx_ >= clib_atomic_load_acq_n (&_c_->state.n_subpools)))                 \
      return 1;                                                                                    \
    _sp_ = vlib_pool_cache_subpool_meta_at (&_c_->state, _pidx_);                                  \
    return clib_atomic_load_acq_n (&_sp_->slot_state[_elt_index_]) !=                              \
	   VLIB_POOL_CACHE_SLOT_ALLOCATED;                                                         \
  }                                                                                                \
                                                                                                   \
  /* Fast path: allocate from the calling thread's owned partial subpool. */                       \
  static_always_inline u32 NAME##_pool_cache_alloc (NAME##_pool_cache_t *_c_)                      \
  {                                                                                                \
    u32 _thread_index_ = vlib_get_thread_index ();                                                 \
    vlib_pool_cache_thread_t *_pt_ = vec_elt_at_index (_c_->state.per_thread, _thread_index_);     \
    u32 _pidx_, _elt_index_;                                                                       \
    vlib_pool_cache_subpool_meta_t *_sp_;                                                          \
    T *_e_, *_pool_;                                                                               \
    if (PREDICT_FALSE (clib_atomic_load_acq_n (&_pt_->remote_pending_subpools) !=                  \
		       VLIB_POOL_CACHE_INVALID_INDEX))                                             \
      NAME##_pool_cache_drain_remote_ (_c_, _pt_, _thread_index_);                                 \
    if (PREDICT_FALSE (_pt_->current_subpool == VLIB_POOL_CACHE_INVALID_INDEX))                    \
      NAME##_pool_cache_alloc_slow_ (_c_, _pt_, _thread_index_);                                   \
    /* current_subpool is the head of the owner-local partial list. This                           \
     * path is single-writer because only the owner thread mutates the list. */                    \
    _pidx_ = _pt_->current_subpool;                                                                \
    ASSERT (_pidx_ != VLIB_POOL_CACHE_INVALID_INDEX);                                              \
    _pool_ = NAME##_pool_cache_pool_at_ (_c_, _pidx_);                                             \
    pool_get (_pool_, _e_);                                                                        \
    _elt_index_ = _e_ - _pool_;                                                                    \
    _sp_ = vlib_pool_cache_subpool_meta_at (&_c_->state, _pidx_);                                  \
    {                                                                                              \
      u8 _expected_ = VLIB_POOL_CACHE_SLOT_FREE;                                                   \
      if (!__atomic_compare_exchange_n (&_sp_->slot_state[_elt_index_], &_expected_,               \
					VLIB_POOL_CACHE_SLOT_ALLOCATED, 0, __ATOMIC_ACQ_REL,       \
					__ATOMIC_RELAXED))                                         \
	{                                                                                          \
	  ASSERT (0);                                                                              \
	  clib_atomic_store_rel_n (&_sp_->slot_state[_elt_index_],                                 \
				   VLIB_POOL_CACHE_SLOT_ALLOCATED);                                \
	}                                                                                          \
    }                                                                                              \
    if (PREDICT_FALSE (pool_free_elts (_pool_) == 0))                                              \
      NAME##_pool_cache_owner_remove_free_ (_c_, _pt_, _pidx_);                                    \
    return vlib_pool_cache_encode_index (&_c_->state, _pidx_, _elt_index_);                        \
  }                                                                                                \
                                                                                                   \
  /* Checked free helper: returns zero for duplicate/stale frees before they can                   \
   * corrupt the backing pool or remote-free stack. */                                             \
  static_always_inline int NAME##_pool_cache_free_internal_ (NAME##_pool_cache_t *_c_, u32 _idx_)  \
  {                                                                                                \
    u32 _thread_index_ = vlib_get_thread_index ();                                                 \
    u32 _pidx_ = vlib_pool_cache_subpool_index (&_c_->state, _idx_);                               \
    u32 _elt_index_ = vlib_pool_cache_elt_index (&_c_->state, _idx_);                              \
    vlib_pool_cache_subpool_meta_t *_sp_;                                                          \
    u32 _owner_;                                                                                   \
    if (PREDICT_FALSE (_pidx_ >= clib_atomic_load_acq_n (&_c_->state.n_subpools)))                 \
      return 0;                                                                                    \
    _sp_ = vlib_pool_cache_subpool_meta_at (&_c_->state, _pidx_);                                  \
    _owner_ = clib_atomic_load_acq_n (&_sp_->owner_thread_index);                                  \
    if (PREDICT_TRUE (_owner_ == _thread_index_))                                                  \
      {                                                                                            \
	vlib_pool_cache_thread_t *_pt_ = vec_elt_at_index (_c_->state.per_thread, _thread_index_); \
	T *_pool_ = NAME##_pool_cache_pool_at_ (_c_, _pidx_);                                      \
	u8 _expected_ = VLIB_POOL_CACHE_SLOT_ALLOCATED;                                            \
	if (!__atomic_compare_exchange_n (&_sp_->slot_state[_elt_index_], &_expected_,             \
					  VLIB_POOL_CACHE_SLOT_FREE, 0, __ATOMIC_ACQ_REL,          \
					  __ATOMIC_RELAXED))                                       \
	  return 0;                                                                                \
	/* Same-owner free is the cheap case: mutate the fixed pool directly, then                 \
	 * update owner-local/free-depot state based on the new occupancy. */                      \
	pool_put_index (_pool_, _elt_index_);                                                      \
	if (PREDICT_FALSE (pool_elts (_pool_) == 0))                                               \
	  NAME##_pool_cache_release_empty_ (_c_, _pt_, _pidx_);                                    \
	else if (pool_free_elts (_pool_) > 0)                                                      \
	  NAME##_pool_cache_owner_add_free_ (_c_, _pt_, _pidx_);                                   \
      }                                                                                            \
    else                                                                                           \
      {                                                                                            \
	/* Cross-thread free keeps the owner as the only writer to the fixed pool. */              \
	if (!NAME##_pool_cache_remote_free_ (_c_, _pidx_, _elt_index_))                            \
	  return 0;                                                                                \
      }                                                                                            \
    return 1;                                                                                      \
  }                                                                                                \
                                                                                                   \
  /* Fast path: owner frees locally; non-owners publish to remote-free stack. */                   \
  static_always_inline void NAME##_pool_cache_free (NAME##_pool_cache_t *_c_, u32 _idx_)           \
  {                                                                                                \
    int _ok_ = NAME##_pool_cache_free_internal_ (_c_, _idx_);                                      \
    ASSERT (_ok_);                                                                                 \
  }                                                                                                \
                                                                                                   \
  static vlib_pool_cache_registration_t NAME##_pool_cache_registration

#endif /* included_vlib_pool_cache_h */
