/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright (c) 2026 Cisco and/or its affiliates.
 */

/*
 * vlib_pool_cache: per-thread cache layered on top of a vppinfra pool.
 *
 * This is the classic "magazine" allocator pattern: a single backing pool
 * is guarded by a spinlock, and each worker thread keeps a thread-local
 * vector of pre-allocated indices. Workers alloc/free against the local
 * cache (lock-free fast path); on cache miss/overflow they bulk
 * refill/drain from the backing pool under the spinlock, amortizing the
 * lock cost over many operations.
 *
 * The backing pool is owned by the wrapper and exposed only through typed
 * accessors generated by VLIB_POOL_CACHE_DEFINE. Callers never touch a
 * raw pool pointer, so they cannot accidentally race against the cache
 * by allocating directly. Alignment is configured per-instance and used
 * by every backing-pool operation (refill and pre-alloc).
 *
 * Single-thread (no workers) is special-cased: the lock is left
 * uninitialized and the per-thread vector is never allocated. Fast path
 * falls through to a direct pool_get_aligned / pool_put_index — zero
 * overhead beyond a predicted-true branch.
 *
 * Usage:
 *
 *   1. Drop the instantiation macro at file scope (in a .c, OR in a
 *      shared header if other TUs need the typed accessors):
 *
 *        VLIB_POOL_CACHE_DEFINE (flow, vnet_flow_t)
 *
 *      That generates:
 *        - flow_pool_cache_t            (typed wrapper struct)
 *        - flow_pool_cache_init         (constructor)
 *        - flow_pool_cache_free_resources
 *        - flow_pool_cache_alloc        (returns u32 index)
 *        - flow_pool_cache_free         (push index back)
 *        - flow_pool_cache_pre_alloc    (grow backing pool ahead of time)
 *        - flow_pool_cache_elt_at_index (idx -> T *)
 *        - flow_pool_cache_is_free_index
 *
 *      Iteration uses the generic macro vlib_pool_cache_foreach (defined
 *      once at the bottom of this header — works for any wrapper since
 *      every wrapper has the same _pool field name).
 *
 *   2. Embed the typed wrapper in your main struct and init it:
 *
 *        typedef struct {
 *          flow_pool_cache_t flows;   // owns the backing pool
 *          ...
 *        } my_main_t;
 *
 *        flow_pool_cache_init (&mm->flows, "flow", 256, CLIB_CACHE_LINE_BYTES);
 *
 *   3. Use the typed API:
 *
 *        u32 idx = flow_pool_cache_alloc (&mm->flows);
 *        vnet_flow_t *f = flow_pool_cache_elt_at_index (&mm->flows, idx);
 *        ...
 *        flow_pool_cache_free (&mm->flows, idx);
 *
 *        vlib_pool_cache_foreach (f, &mm->flows) { ... }
 *
 *      To pre-grow the pool (e.g. before workers start hammering it):
 *
 *        flow_pool_cache_pre_alloc (&mm->flows, n);
 *
 * Notes:
 * - The cache stores u32 pool indices, not elements or pointers. Pool
 *   indices are stable across allocations (vppinfra pool guarantee), so
 *   workers can safely cache them across refill cycles.
 * - The per-thread cache vector is cache-line padded to avoid false
 *   sharing between adjacent worker threads.
 * - Alignment is the byte alignment passed to pool_get_aligned. Pass 0
 *   for natural alignment, or e.g. CLIB_CACHE_LINE_BYTES.
 */

#ifndef included_vlib_pool_cache_h
#define included_vlib_pool_cache_h

#include <vlib/vlib.h>
#include <vppinfra/cache.h>
#include <vppinfra/lock.h>
#include <vppinfra/pool.h>
#include <vppinfra/vec.h>

#define VLIB_POOL_CACHE_DEFAULT_SIZE 256

typedef struct
{
  CLIB_CACHE_LINE_ALIGN_MARK (cacheline0);
  u32 *cache; /* per-thread vec of pool indices */
} vlib_pool_cache_thread_t;

/*
 * Type-agnostic state common to every pool_cache instance. Embedded by
 * value in the typed wrapper struct generated by VLIB_POOL_CACHE_DEFINE;
 * not used directly by callers.
 */
typedef struct
{
  /* Spinlock guarding the backing pool. Left uninitialized when no
   * workers are configured: in that case the cache is bypassed. */
  clib_spinlock_t lock;

  /* Per-thread caches, indexed by vlib_get_thread_index().
   * NULL when no workers (single-thread fast path). */
  vlib_pool_cache_thread_t *per_thread;

  /* Number of indices to keep cached per worker (default 256). */
  u32 cache_size;

  /* Drain back to the backing pool when the local cache exceeds this
   * many entries (default 2 * cache_size). */
  u32 drain_threshold;

  /* Byte alignment passed to pool_get_aligned / pool_alloc_aligned. */
  u32 align;

  /* For debug / introspection. */
  char *name;
} vlib_pool_cache_t;

void vlib_pool_cache_init_state (vlib_pool_cache_t *c, char *name, u32 cache_size, u32 align);
void vlib_pool_cache_free_state (vlib_pool_cache_t *c);

/*
 * VLIB_POOL_CACHE_DEFINE(NAME, T)
 *
 * Generate a typed wrapper around a pool of T plus a per-thread cache.
 * Drop one of these at file scope. NAME is a caller-chosen prefix used
 * for the generated struct and functions; T is the pool element type.
 *
 * Generated symbols (all static_always_inline so each TU gets a copy and
 * the optimizer can fully inline the fast path):
 *
 *   typedef struct { ... } NAME##_pool_cache_t;
 *   void NAME##_pool_cache_init        (NAME##_pool_cache_t *c, char *name,
 *                                       u32 cache_size, u32 align);
 *   void NAME##_pool_cache_free_resources (NAME##_pool_cache_t *c);
 *   u32  NAME##_pool_cache_alloc       (NAME##_pool_cache_t *c);
 *   void NAME##_pool_cache_free        (NAME##_pool_cache_t *c, u32 idx);
 *   void NAME##_pool_cache_pre_alloc   (NAME##_pool_cache_t *c, u32 n);
 *   T *  NAME##_pool_cache_elt_at_index(NAME##_pool_cache_t *c, u32 idx);
 *   int  NAME##_pool_cache_is_free_index (NAME##_pool_cache_t *c, u32 idx);
 *
 * Iteration is via the generic vlib_pool_cache_foreach(VAR, C) macro
 * defined at the bottom of this header — it works for any wrapper since
 * every wrapper shares the same _pool field name.
 *
 * The pool itself (T *_pool) is a private field of the wrapper struct.
 * Callers MUST NOT touch it directly: bypassing the typed API would race
 * against the cache.
 */
#define VLIB_POOL_CACHE_DEFINE(NAME, T)                                                            \
                                                                                                   \
  /* Typed wrapper. _pool is private to the generated accessors. */                                \
  typedef struct                                                                                   \
  {                                                                                                \
    T *_pool;                                                                                      \
    vlib_pool_cache_t state;                                                                       \
  } NAME##_pool_cache_t;                                                                           \
                                                                                                   \
  /* Slow path: bulk-move cache_size indices from the backing pool to the local cache              \
   * under the spinlock. */                                                                        \
  static_always_inline void NAME##_pool_cache_refill_ (NAME##_pool_cache_t *_c_,                   \
						       vlib_pool_cache_thread_t *_pt_)             \
  {                                                                                                \
    T *_e_;                                                                                        \
    u32 _i_;                                                                                       \
    clib_spinlock_lock (&_c_->state.lock);                                                         \
    for (_i_ = 0; _i_ < _c_->state.cache_size; _i_++)                                              \
      {                                                                                            \
	pool_get_aligned (_c_->_pool, _e_, _c_->state.align);                                      \
	vec_add1 (_pt_->cache, _e_ - _c_->_pool);                                                  \
      }                                                                                            \
    clib_spinlock_unlock (&_c_->state.lock);                                                       \
  }                                                                                                \
                                                                                                   \
  /* Slow path: drain the overflow back to the backing pool until exactly cache_size               \
   * entries remain locally. */                                                                    \
  static_always_inline void NAME##_pool_cache_drain_ (NAME##_pool_cache_t *_c_,                    \
						      vlib_pool_cache_thread_t *_pt_)              \
  {                                                                                                \
    if (PREDICT_FALSE (vec_len (_pt_->cache) <= _c_->state.cache_size))                            \
      return;                                                                                      \
    u32 _n_ = vec_len (_pt_->cache) - _c_->state.cache_size;                                       \
    u32 _i_;                                                                                       \
    clib_spinlock_lock (&_c_->state.lock);                                                         \
    for (_i_ = 0; _i_ < _n_; _i_++)                                                                \
      {                                                                                            \
	u32 _idx_ = vec_pop (_pt_->cache);                                                         \
	pool_put_index (_c_->_pool, _idx_);                                                        \
      }                                                                                            \
    clib_spinlock_unlock (&_c_->state.lock);                                                       \
  }                                                                                                \
                                                                                                   \
  /* Construct an empty cache. The backing pool starts at zero size; it grows on demand            \
   * via refill, or eagerly via NAME##_pool_cache_pre_alloc. */                                    \
  static_always_inline void NAME##_pool_cache_init (NAME##_pool_cache_t *_c_, char *_name_,        \
						    u32 _cache_size_, u32 _align_)                 \
  {                                                                                                \
    _c_->_pool = 0;                                                                                \
    vlib_pool_cache_init_state (&_c_->state, _name_, _cache_size_, _align_);                       \
  }                                                                                                \
                                                                                                   \
  /* Release the backing pool and all per-thread cache state. Caller must ensure no                \
   * worker is still alloc'ing/freeing. */                                                         \
  static_always_inline void NAME##_pool_cache_free_resources (NAME##_pool_cache_t *_c_)            \
  {                                                                                                \
    pool_free (_c_->_pool);                                                                        \
    vlib_pool_cache_free_state (&_c_->state);                                                      \
  }                                                                                                \
                                                                                                   \
  /* Eagerly grow the backing pool to hold at least N elements, so workers don't trigger a         \
   * realloc on the data path. Takes the lock so it's safe with workers running. */                \
  static_always_inline void NAME##_pool_cache_pre_alloc (NAME##_pool_cache_t *_c_, u32 _n_)        \
  {                                                                                                \
    clib_spinlock_lock_if_init (&_c_->state.lock);                                                 \
    pool_alloc_aligned (_c_->_pool, _n_, _c_->state.align);                                        \
    clib_spinlock_unlock_if_init (&_c_->state.lock);                                               \
  }                                                                                                \
                                                                                                   \
  /* Resolve a pool index to its element pointer. */                                               \
  static_always_inline T *NAME##_pool_cache_elt_at_index (NAME##_pool_cache_t *_c_, u32 _idx_)     \
  {                                                                                                \
    return pool_elt_at_index (_c_->_pool, _idx_);                                                  \
  }                                                                                                \
                                                                                                   \
  /* Test whether a pool index is currently free (matches pool_is_free_index semantics). */        \
  static_always_inline int NAME##_pool_cache_is_free_index (NAME##_pool_cache_t *_c_, u32 _idx_)   \
  {                                                                                                \
    return pool_is_free_index (_c_->_pool, _idx_);                                                 \
  }                                                                                                \
                                                                                                   \
  /* Fast path: pop one index off the calling thread's local cache (refilling on miss). In         \
   * single-thread mode falls through to a direct pool_get_aligned, no lock taken. */              \
  static_always_inline u32 NAME##_pool_cache_alloc (NAME##_pool_cache_t *_c_)                      \
  {                                                                                                \
    u32 _idx_;                                                                                     \
    if (PREDICT_TRUE (_c_->state.per_thread != 0))                                                 \
      {                                                                                            \
	vlib_pool_cache_thread_t *_pt_ =                                                           \
	  vec_elt_at_index (_c_->state.per_thread, vlib_get_thread_index ());                      \
	if (PREDICT_FALSE (vec_len (_pt_->cache) == 0))                                            \
	  NAME##_pool_cache_refill_ (_c_, _pt_);                                                   \
	_idx_ = vec_pop (_pt_->cache);                                                             \
      }                                                                                            \
    else                                                                                           \
      {                                                                                            \
	T *_e_;                                                                                    \
	pool_get_aligned (_c_->_pool, _e_, _c_->state.align);                                      \
	_idx_ = _e_ - _c_->_pool;                                                                  \
      }                                                                                            \
    return _idx_;                                                                                  \
  }                                                                                                \
                                                                                                   \
  /* Fast path: push one index back onto the calling thread's local cache. Drains to the           \
   * backing pool when the cache exceeds drain_threshold. In single-thread mode falls              \
   * through to a direct pool_put_index, no lock taken. */                                         \
  static_always_inline void NAME##_pool_cache_free (NAME##_pool_cache_t *_c_, u32 _idx_)           \
  {                                                                                                \
    if (PREDICT_TRUE (_c_->state.per_thread != 0))                                                 \
      {                                                                                            \
	vlib_pool_cache_thread_t *_pt_ =                                                           \
	  vec_elt_at_index (_c_->state.per_thread, vlib_get_thread_index ());                      \
	vec_add1 (_pt_->cache, _idx_);                                                             \
	if (PREDICT_FALSE (vec_len (_pt_->cache) > _c_->state.drain_threshold))                    \
	  NAME##_pool_cache_drain_ (_c_, _pt_);                                                    \
      }                                                                                            \
    else                                                                                           \
      {                                                                                            \
	pool_put_index (_c_->_pool, _idx_);                                                        \
      }                                                                                            \
  }

/*
 * vlib_pool_cache_foreach(VAR, C) — iterate live elements of the backing
 * pool. Generic across every wrapper because all wrappers share the same
 * private _pool field name. Wraps the pool_foreach macro from pool.h, so
 * VAR's type is inferred from (C)->_pool[0].
 *
 * NOT thread-safe against concurrent alloc/free; intended for admin/CLI
 * paths only.
 */
#define vlib_pool_cache_foreach(VAR, C) pool_foreach (VAR, (C)->_pool)

#endif /* included_vlib_pool_cache_h */
