#ifndef __included_dpdk_cpu_h__
#define __included_dpdk_cpu_h__

/* Disable some CPU features at the DPDK level, depending on the current variant */

#define DPDK_AES_nhm 0
#define DPDK_AVX_nhm 0
#define DPDK_AVX2_nhm 0
#define DPDK_AVX512F_nhm 0
#define DPDK_PCLMULQDQ_nhm 0
#define DPDK_RDRAND_nhm 0
#define DPDK_RDSEED_nhm 0

#define DPDK_AES_hsw 1
#define DPDK_AVX_hsw 1
#define DPDK_AVX2_hsw 1
#define DPDK_AVX512F_hsw 0
#define DPDK_PCLMULQDQ_hsw 1
#define DPDK_RDRAND_hsw 1
#define DPDK_RDSEED_hsw 0

#define DPDK_AES_skx 1
#define DPDK_AVX_skx 1
#define DPDK_AVX2_skx 1
#define DPDK_AVX512F_skx 1
#define DPDK_PCLMULQDQ_skx 1
#define DPDK_RDRAND_skx 1
#define DPDK_RDSEED_skx 1

#ifdef CLIB_MARCH_VARIANT
#define DPDK_MARCH_VARIANT CLIB_MARCH_VARIANT
#else
#define DPDK_MARCH_VARIANT nhm
#endif

#undef RTE_MACHINE_CPUFLAG_AES
#undef RTE_MACHINE_CPUFLAG_AVX
#undef RTE_MACHINE_CPUFLAG_AVX2
#undef RTE_MACHINE_CPUFLAG_AVX512F
#undef RTE_MACHINE_CPUFLAG_PCLMULQDQ
#undef RTE_MACHINE_CPUFLAG_RDRAND
#undef RTE_MACHINE_CPUFLAG_RDSEED

#define RTE_MACHINE_CPUFLAG_AES DPDK_AES_##DPDK_MARCH_VARIANT
#define RTE_MACHINE_CPUFLAG_AVX DPDK_AVX_##DPDK_MARCH_VARIANT
#define RTE_MACHINE_CPUFLAG_AVX2 DPDK_AVX2_##DPDK_MARCH_VARIANT
#define RTE_MACHINE_CPUFLAG_AVX512F DPDK_AVX512F_##DPDK_MARCH_VARIANT
#define RTE_MACHINE_CPUFLAG_PCLMULQDQ DPDK_PCLMMULQDQ_##DPDK_MARCH_VARIANT
#define RTE_MACHINE_CPUFLAG_RDRAND DPDK_RDRAND_##DPDK_MARCH_VARIANT
#define RTE_MACHINE_CPUFLAG_RDSEED DPDK_RDSEED_##DPDK_MARCH_VARIANT

#if RTE_MACHINE_CPUFLAG_AES==0
#undef RTE_MACHINE_CPUFLAG_AES
#endif
#if RTE_MACHINE_CPUFLAG_AVX==0
#undef RTE_MACHINE_CPUFLAG_AVX
#endif
#if RTE_MACHINE_CPUFLAG_AVX2==0
#undef RTE_MACHINE_CPUFLAG_AVX2
#endif
#if RTE_MACHINE_CPUFLAG_AVX512F==0
#undef RTE_MACHINE_CPUFLAG_AVX512F
#endif
#if RTE_MACHINE_CPUFLAG_PCLMULQDQ==0
#undef RTE_MACHINE_CPUFLAG_PCLMULQDQ
#endif
#if RTE_MACHINE_CPUFLAG_RDRAND==0
#undef RTE_MACHINE_CPUFLAG_RDRAND
#endif
#if RTE_MACHINE_CPUFLAG_RDSEED==0
#undef RTE_MACHINE_CPUFLAG_RDSEED
#endif

#endif