---
name: "🛠️ VPP Install Optional Dependencies"
description: |
  This GitHub Action installs the necessary optional dependencies for VPP.

inputs:
  WORKSPACE:
    description: "Workspace directory where VPP is located"
    required: true
    type: string
  TUI_LINE:
    description: "Delimiter line for TUI output"
    required: false
    default: "*******************************************************************"
    type: string

runs:
  using: "composite"
  steps:
    - name: Install Optional Dependencies
      shell: bash
      env:
        WORKSPACE: ${{ inputs.WORKSPACE }}
        TUI_LINE: ${{ inputs.TUI_LINE }}
      run: |
        set -euo pipefail
        cd "$WORKSPACE"
        echo -e "$TUI_LINE\nInstalling VPP optional dependencies...\n"
        make UNATTENDED=yes install-opt-deps
        echo "$TUI_LINE"