#!/usr/bin/env bash

# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025 Cisco Systems, Inc.

VPP_WS=${VPP_WS:-/scratch/fcoras/vpp}
CFG_WS=$VPP_WS/extras/scripts/host-stack/perf-tests
CFG_DIR=$CFG_WS/conf
CFG_FILE=dpdk_mt.cli
BASE_DIR=/scratch/fcoras/vpp/build-root
BIN_FLAVOR=release

DPDK_DEV=0000:16:00.0
NUM_MBUFS=16536
IF_RX_DESC=256
IF_TX_DESC=256
DPDK_CSUM=enable-tcp-udp-checksum

SKIP_CORE=0
MAIN_CORE=1
WORKERS=4
CFG_CORELIST_WKS="corelist-workers 2-5"

HEAP_SIZE=4g
API_SIZE=1G
API_GLOBAL_SIZE=2000M
EVT_LOG_SIZE=400000

SOCK=/run/vpp-api.sock
SESSION_CFG="session { event-queue-length 100000 use-app-socket-api }"

#QUIC_ENABLE=1
#LOCAL_OSSL=/scratch/fcoras/openssl

function usage() {
  echo "Usage: cmd [-f release|debug] [-d dpdk_device_pci_address] [-w vpp_workspace]"
}

while getopts "f:d:h" opt; do
  case ${opt} in
    h)  usage
        exit 0
        ;;
    w)  VPP_WS=$OPTARG
        ;;
    f)  BIN_FLAVOR=$OPTARG
        ;;
    d)  DPDK_DEV=$OPTARG
        ;;
    \?) echo "Usage: cmd [-f release|debug] [-d dpdk_device_pci_address]"
        exit 1
        ;;
  esac
done
shift $((OPTIND -1))

source ~/vpp/start_vpp.sh

start_vpp
