# curl container that uses the base image
ARG UBUNTU_VERSION=22.04
FROM localhost:5001/vpp-test-base:latest

# Note: wget and xz-utils are already in the base image

COPY script/slow_reader.sh /usr/bin/slow_reader.sh
RUN fallocate -l 10MB /tmp/testFile
RUN chmod +x /usr/bin/slow_reader.sh
COPY resources/curl/* /tmp/

# unset proxy vars to avoid "HTTP/3 is not supported over an HTTP proxy" error
# (using --noproxy arg doesn't work)
ENV http_proxy=""
ENV https_proxy=""
ENV HTTP_PROXY=""
ENV HTTPS_PROXY=""

CMD ["/bin/sh"]
