#!/bin/sh
#
# Do all the legwork to run a scapy shell with APIs available for load
#
ROOT_DIR=`git rev-parse --show-toplevel`
cd $ROOT_DIR
sudo apt-get install -y python-virtualenv
# uncomment the line below to enable the build of plugins and API each time..
# make plugins && make build-vpp-api || exit
virtualenv virtualenv
virtualenv/bin/pip install ipaddress
virtualenv/bin/pip install scapy
# install the python API into the virtualenv
cd $ROOT_DIR/vpp-api/python/
$ROOT_DIR/virtualenv/bin/python setup.py install
# install the python ACL plugin API into the virtualenv
ACL_PLUGIN_SETUP_DIR=`find $ROOT_DIR/build-root -name acl-plugin`
cd $ACL_PLUGIN_SETUP_DIR; 
$ROOT_DIR/virtualenv/bin/python setup.py install
cd $ROOT_DIR
# figure out the shared library path and start scapy
export LD_LIBRARY_PATH=`pwd`/`find . -name "libpneum.so" -exec dirname {} \; | grep lib64 | head -n 1`
sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH virtualenv/bin/scapy



