# Download base ubuntu image
FROM centos:centos7
ARG VPP_EXACT_VERSION
ARG PACKAGECLOUD_REPO
ARG VPP_CHECK_VERSION

# install main packages:
RUN yum -y update; yum clean all;


RUN yum -y update; yum clean all;
RUN yum -y install epel-release; yum clean all
RUN yum -y install curl sudo gawk; yum clean all

# "=19.01.2-release" for example, or empty
ENV VPP_VERSION_ARG=${VPP_EXACT_VERSION:+-${VPP_EXACT_VERSION}.x86_64}
RUN export VPP_VERSION_ARG

RUN echo ${VPP_CHECK_VERSION} > /VPP_CHECK_VERSION.txt


# install fd.io repo
RUN (curl -s https://packagecloud.io/install/repositories/${PACKAGECLOUD_REPO}/script.rpm.sh | sudo bash)
#RUN yum -y update; yum clean all;

RUN yum -y install vpp${VPP_VERSION_ARG} libvppinfra${VPP_VERSION_ARG} libvppinfra-dev${VPP_VERSION_ARG} vpp-plugin-core${VPP_VERSION_ARG} vpp-plugin-dpdk${VPP_VERSION_ARG} vpp-api-python${VPP_VERSION_ARG} python3-vpp-api${VPP_VERSION_ARG} vpp-dbg${VPP_VERSION_ARG} vpp-dev${VPP_VERSION_ARG}; yum clean all

COPY start.sh /start.sh
COPY vpp-commands.txt /vpp-commands.txt

CMD ["./start.sh"]

# EXPOSE 1234


