// Code generated by MockGen. DO NOT EDIT.
// Source: go.fd.io/govpp/api (interfaces: Channel)
//
// Generated by this command:
//
//	mockgen -package main -destination apimock.go go.fd.io/govpp/api Channel
//

// Package main is a generated GoMock package.
package main

import (
	reflect "reflect"
	time "time"

	api "go.fd.io/govpp/api"
	gomock "go.uber.org/mock/gomock"
)

// MockChannel is a mock of Channel interface.
type MockChannel struct {
	ctrl     *gomock.Controller
	recorder *MockChannelMockRecorder
	isgomock struct{}
}

// MockChannelMockRecorder is the mock recorder for MockChannel.
type MockChannelMockRecorder struct {
	mock *MockChannel
}

// NewMockChannel creates a new mock instance.
func NewMockChannel(ctrl *gomock.Controller) *MockChannel {
	mock := &MockChannel{ctrl: ctrl}
	mock.recorder = &MockChannelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannel) EXPECT() *MockChannelMockRecorder {
	return m.recorder
}

// CheckCompatiblity mocks base method.
func (m *MockChannel) CheckCompatiblity(msgs ...api.Message) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range msgs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CheckCompatiblity", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckCompatiblity indicates an expected call of CheckCompatiblity.
func (mr *MockChannelMockRecorder) CheckCompatiblity(msgs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCompatiblity", reflect.TypeOf((*MockChannel)(nil).CheckCompatiblity), msgs...)
}

// Close mocks base method.
func (m *MockChannel) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockChannelMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockChannel)(nil).Close))
}

// SendMultiRequest mocks base method.
func (m *MockChannel) SendMultiRequest(msg api.Message) api.MultiRequestCtx {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMultiRequest", msg)
	ret0, _ := ret[0].(api.MultiRequestCtx)
	return ret0
}

// SendMultiRequest indicates an expected call of SendMultiRequest.
func (mr *MockChannelMockRecorder) SendMultiRequest(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMultiRequest", reflect.TypeOf((*MockChannel)(nil).SendMultiRequest), msg)
}

// SendRequest mocks base method.
func (m *MockChannel) SendRequest(msg api.Message) api.RequestCtx {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendRequest", msg)
	ret0, _ := ret[0].(api.RequestCtx)
	return ret0
}

// SendRequest indicates an expected call of SendRequest.
func (mr *MockChannelMockRecorder) SendRequest(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendRequest", reflect.TypeOf((*MockChannel)(nil).SendRequest), msg)
}

// SetReplyTimeout mocks base method.
func (m *MockChannel) SetReplyTimeout(timeout time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetReplyTimeout", timeout)
}

// SetReplyTimeout indicates an expected call of SetReplyTimeout.
func (mr *MockChannelMockRecorder) SetReplyTimeout(timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReplyTimeout", reflect.TypeOf((*MockChannel)(nil).SetReplyTimeout), timeout)
}

// SubscribeNotification mocks base method.
func (m *MockChannel) SubscribeNotification(notifChan chan api.Message, event api.Message) (api.SubscriptionCtx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeNotification", notifChan, event)
	ret0, _ := ret[0].(api.SubscriptionCtx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeNotification indicates an expected call of SubscribeNotification.
func (mr *MockChannelMockRecorder) SubscribeNotification(notifChan, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeNotification", reflect.TypeOf((*MockChannel)(nil).SubscribeNotification), notifChan, event)
}
