// Code generated by MockGen. DO NOT EDIT.
// Source: go.fd.io/govpp/adapter (interfaces: StatsAPI)
//
// Generated by this command:
//
//	mockgen -package main -destination statsmock.go go.fd.io/govpp/adapter StatsAPI
//

// Package main is a generated GoMock package.
package main

import (
	reflect "reflect"

	adapter "go.fd.io/govpp/adapter"
	gomock "go.uber.org/mock/gomock"
)

// MockStatsAPI is a mock of StatsAPI interface.
type MockStatsAPI struct {
	ctrl     *gomock.Controller
	recorder *MockStatsAPIMockRecorder
	isgomock struct{}
}

// MockStatsAPIMockRecorder is the mock recorder for MockStatsAPI.
type MockStatsAPIMockRecorder struct {
	mock *MockStatsAPI
}

// NewMockStatsAPI creates a new mock instance.
func NewMockStatsAPI(ctrl *gomock.Controller) *MockStatsAPI {
	mock := &MockStatsAPI{ctrl: ctrl}
	mock.recorder = &MockStatsAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsAPI) EXPECT() *MockStatsAPIMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockStatsAPI) Connect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect")
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockStatsAPIMockRecorder) Connect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockStatsAPI)(nil).Connect))
}

// Disconnect mocks base method.
func (m *MockStatsAPI) Disconnect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disconnect")
	ret0, _ := ret[0].(error)
	return ret0
}

// Disconnect indicates an expected call of Disconnect.
func (mr *MockStatsAPIMockRecorder) Disconnect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disconnect", reflect.TypeOf((*MockStatsAPI)(nil).Disconnect))
}

// DumpStats mocks base method.
func (m *MockStatsAPI) DumpStats(patterns ...string) ([]adapter.StatEntry, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range patterns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DumpStats", varargs...)
	ret0, _ := ret[0].([]adapter.StatEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DumpStats indicates an expected call of DumpStats.
func (mr *MockStatsAPIMockRecorder) DumpStats(patterns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DumpStats", reflect.TypeOf((*MockStatsAPI)(nil).DumpStats), patterns...)
}

// ListStats mocks base method.
func (m *MockStatsAPI) ListStats(patterns ...string) ([]adapter.StatIdentifier, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range patterns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListStats", varargs...)
	ret0, _ := ret[0].([]adapter.StatIdentifier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStats indicates an expected call of ListStats.
func (mr *MockStatsAPIMockRecorder) ListStats(patterns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStats", reflect.TypeOf((*MockStatsAPI)(nil).ListStats), patterns...)
}

// PrepareDir mocks base method.
func (m *MockStatsAPI) PrepareDir(patterns ...string) (*adapter.StatDir, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range patterns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PrepareDir", varargs...)
	ret0, _ := ret[0].(*adapter.StatDir)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareDir indicates an expected call of PrepareDir.
func (mr *MockStatsAPIMockRecorder) PrepareDir(patterns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareDir", reflect.TypeOf((*MockStatsAPI)(nil).PrepareDir), patterns...)
}

// PrepareDirOnIndex mocks base method.
func (m *MockStatsAPI) PrepareDirOnIndex(indexes ...uint32) (*adapter.StatDir, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range indexes {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PrepareDirOnIndex", varargs...)
	ret0, _ := ret[0].(*adapter.StatDir)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareDirOnIndex indicates an expected call of PrepareDirOnIndex.
func (mr *MockStatsAPIMockRecorder) PrepareDirOnIndex(indexes ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareDirOnIndex", reflect.TypeOf((*MockStatsAPI)(nil).PrepareDirOnIndex), indexes...)
}

// UpdateDir mocks base method.
func (m *MockStatsAPI) UpdateDir(dir *adapter.StatDir) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDir", dir)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDir indicates an expected call of UpdateDir.
func (mr *MockStatsAPIMockRecorder) UpdateDir(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDir", reflect.TypeOf((*MockStatsAPI)(nil).UpdateDir), dir)
}
