l2tp_set_lookup_key lookup_v6_src

sw_interface_add_del_address GigabitEthernet2/3/0 db03::2/64
sw_interface_set_flags GigabitEthernet2/3/0 admin-up

comment sw_interface_add_del_address GigabitEthernet2/2/0 db02::2/64
sw_interface_set_flags GigabitEthernet2/2/0 admin-up

l2tp_session_add_del client_address db03::1 our_address db03::2 GigabitEthernet2/2/0 local_session_id 1 remote_session_id 3 local_cookie 11 remote_cookie 33
