
# Build vpp_stats_fs

.PHONY: install
install:
	@./install.sh install

.PHONY: start
start:
	@./install.sh start

.PHONY: clean
clean:
	@./install.sh clean

.PHONY: help
help:
	@./install.sh help

.PHONY: force-unmount
force-unmount:
	@./install.sh unmount

.PHONY: stop
stop:
	@./install.sh stop