kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  podSubnet: "11.0.0.0/16"
  serviceSubnet: "11.96.0.0/12"
nodes:
- role: control-plane
- role: worker
- role: worker