#!/usr/bin/env python3

huff_sym_table = []

with open("rfc7541_huffman_code.txt") as f:
    while line := f.readline():
        l = line.rstrip().split("  ")
        code_len = l[-1][1:-1].strip()
        code = l[-2].strip()
        huff_sym_table.append((code_len, code))

f = open("../huffman_table.h", "w")
f.write(
    """/* SPDX-License-Identifier: Apache-2.0
 * Copyright(c) 2025 Cisco Systems, Inc.
 */

/* generated by mk_huffman_table.py */

#ifndef SRC_PLUGINS_HTTP_HUFFMAN_TABLE_H_
#define SRC_PLUGINS_HTTP_HUFFMAN_TABLE_H_

#include <vppinfra/types.h>

typedef struct
{
  u8 code_len;
  u32 code;
} http_huffman_symbol_t;

static http_huffman_symbol_t huff_sym_table[] = {
"""
)

[f.write("  {" + sym[0] + ", 0x" + sym[1] + "},\n") for sym in huff_sym_table]

f.write(
    """};

#endif /* SRC_PLUGINS_HTTP_HUFFMAN_TABLE_H_ */
"""
)

f.close()
