#!/bin/bash

if [ -z $1 ]; then
	echo "Please specify path"
	exit 1
fi

which p1atchelf &> /dev/null

if [ $? -ne 0 ] ; then
	echo "Please install patchelf tool"
	exit 1
fi

libs=$(find $1 -type f -name \*.so)
execs=$(find $1 -type f -path \*/bin/\* )

for i in $libs $execs; do
	patchelf --print-rpath $i 2> /dev/null | grep -q build-root
	if [ $? -eq 0 ] ; then
		patchelf --remove-rpath $i
	fi
done

