#!/bin/bash

TAG=$(git describe | cut -d- -f1 | sed -e 's/^v//')
ADD=$(git describe | cut -s -d- -f2)
CMT=$(git describe --dirty --match 'v*'| cut -s -d- -f3,4)

if [ -n "${BUILD_NUMBER}" ]; then
       BLD="~b${BUILD_NUMBER}"
fi

if [ "$1" = "rpm-version" ]; then
  echo ${TAG}
  exit
fi

if [ "$1" = "rpm-release" ]; then
  [ -z "${ADD}" ] && echo release && exit
  CMT=$(git describe --dirty --match 'v*'| cut -s -d- -f3,4 | sed 's/-/_/')
  echo ${ADD}${CMT:+~${CMT}}${BLD}
  exit
fi

if [ -n "${ADD}" ]; then
  echo ${TAG}-${ADD}${CMT:+~${CMT}}${BLD}
else
  echo ${TAG}
fi
